// app/(auth)/game/pools/flashJudgePools.ts
import type { QuizType } from "@/app/data/types"
import type { FlashJudgeQuestion } from "../types"

// ✅ まずは N4 の実運用を想定したサンプルを同梱
// - 将来は Firestore / 管理画面 から差し替え可能

export const flashJudgePools: Partial<Record<QuizType, FlashJudgeQuestion[]>> = {
  "japanese-n4": [
    
    // ✅ 文法のみ（N4）
    {
      id: "fj-n4-j-001",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "昨日は どこへも 行きました。",
      answer: false,
      explanation: "否定の「～も」の後ろは「行きませんでした」が正解。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-002",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "漢字を 書くのは 難しいです。",
      answer: true,
      explanation: "動詞を名詞にする「の」の正しい使い方。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-003",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "明日 雨が 降ったら、ピクニックに 行きません。",
      answer: true,
      explanation: "「～たら」を使った条件表現。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-004",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 田中さんに 英語を 教えて もらいました。",
      answer: true,
      explanation: "恩恵を受ける「～てもらう」の表現。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-005",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "部屋が 暗いですから、電気を 消してください。",
      answer: false,
      explanation: "暗いときは電気を「つけて」ください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-006",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "日本語を 上手になりたいです。",
      answer: false,
      explanation: "正解は「日本語『が』上手になりたい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-007",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "この ケーキは 甘そうです。",
      answer: true,
      explanation: "見た目から推測する「～そうです」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-008",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "30分も 待ちましたが、バスは 来ませんでした。",
      answer: true,
      explanation: "驚きや不満を表す強調の「も」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-009",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "教室で タバコを 吸っても いいです。",
      answer: false,
      explanation: "一般的なマナーとして吸ってはいけません。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-010",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "窓が 閉まっています。",
      answer: true,
      explanation: "状態を表す「～ています（自動詞）」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-011",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「案内」は 道や 場所を 教えることです。",
      answer: true,
      explanation: "N4必須語彙の意味。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-012",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「去年」は 今年の 次の 年のことです。",
      answer: false,
      explanation: "去年は「前の年」、次の年は「来年」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-013",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「お辞儀」は 頭を 下げて あいさつすることです。",
      answer: true,
      explanation: "日本の文化・語彙。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-014",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「複雑」は 易しくて 分かりやすいことです。",
      answer: false,
      explanation: "複雑は「難しくて分かりにくい」こと。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-015",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「都合」は 時間や 事情が 良いか どうかです。",
      answer: true,
      explanation: "N4レベルの重要単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-016",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "作業が終わったら、道具は 出したままにする。",
      answer: false,
      explanation: "「使ったら片付ける」が安全の基本です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-017",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "ヘルメットの 紐は ゆるめて かぶる。",
      answer: false,
      explanation: "紐はしっかり締めないと、事故の時に脱げます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-018",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "機械が 動いているときは、絶対に 手を 入れない。",
      answer: true,
      explanation: "重大な事故を防ぐ鉄則です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-019",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "指差呼称は、ミスを 防ぐために 大切です。",
      answer: true,
      explanation: "「よし！」と確認する大事な習慣。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-020",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "重い荷物を 持つときは、膝を 曲げずに 腰だけで 持つ。",
      answer: false,
      explanation: "腰を痛めるので、膝を曲げて持つのが正解。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-021",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "お酒を 飲みすぎて、頭が 痛いです。",
      answer: true,
      explanation: "過剰を表す「～すぎる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-022",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "この薬は 苦いですが、飲んだほうが いいです。",
      answer: true,
      explanation: "アドバイスの「～ほうがいい」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-023",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "電車を 降りる前に、ドアが 開きました。",
      answer: true,
      explanation: "時間の前後を表す「前に」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-024",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 母に 掃除を させられました。",
      answer: true,
      explanation: "使役受身「～させられる（嫌だけどやった）」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-025",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "日本語が 全然 分かります。",
      answer: false,
      explanation: "「全然」の後ろは「分かりません（否定）」が正解。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-026",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「失敗」は うまく いかないことです。",
      answer: true,
      explanation: "N4単語の意味。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-027",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「親切」は 意地悪な 人のことです。",
      answer: false,
      explanation: "親切は「優しい人」のこと。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-028",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「将来」は ずっと 前の 時間のことです。",
      answer: false,
      explanation: "将来は「これから先の時間（未来）」のこと。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-029",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "宿題を しながら、音楽を 聞きます。",
      answer: true,
      explanation: "同時動作の「～ながら」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-030",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "田中さんは もう 帰ったと 思います。",
      answer: true,
      explanation: "意見や推測の「～と思う」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-031",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "工場の中は、右側か左側、決められた場所を歩く。",
      answer: true,
      explanation: "通路のルールを守るのが安全です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-032",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "濡れた手で、電気のスイッチを 触ってもいい。",
      answer: false,
      explanation: "感電する危険があるので、絶対にダメ。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-033",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "非常口の前に、荷物を 置いてはいけない。",
      answer: true,
      explanation: "火事などの時に逃げられなくなります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-034",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "先生、お茶を 飲みますか。（丁寧な表現）",
      answer: true,
      explanation: "N4レベルの基本的な敬体。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-035",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "召し上がってください。",
      answer: true,
      explanation: "「食べてください」の尊敬語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-036",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "テレビが 消えて あります。",
      answer: false,
      explanation: "正解は「消して あります（他動詞）」または「消えています」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-037",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "日本語は 漢字が ありますから 難しいです。",
      answer: true,
      explanation: "理由を表す「～から」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-038",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "毎日 1時間 走ることに しています。",
      answer: true,
      explanation: "習慣・決心を決める「～ことにしている」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-039",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "明日 晴れるかどうか、分かりません。",
      answer: true,
      explanation: "疑問を含む文「～かどうか」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-040",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「趣味」は 自分が 好きな 遊びのことです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-041",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "油が 床に こぼれていたら、すぐに 拭く。",
      answer: true,
      explanation: "滑って転ぶ事故を防ぎます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-042",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "作業着が 汚れていても、安全には 関係ない。",
      answer: false,
      explanation: "汚れから機械に巻き込まれることもあるので清潔に。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-043",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "疲れているときは、無理をして 作業を 続ける。",
      answer: false,
      explanation: "集中力が落ちて事故が起きやすいので、休憩が必要。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-044",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私の夢は 医者に なることです。",
      answer: true,
      explanation: "「名詞修飾＋こと」の形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-045",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "コーヒーに 砂糖を 入れずに 飲みます。",
      answer: true,
      explanation: "「～ないで」と同じ意味の「～ずに」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-046",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "図書館で 大きな声で 話さないでください。",
      answer: true,
      explanation: "禁止・依頼の「～ないでください」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-047",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "田中さんは どこに いるか 知っていますか。",
      answer: true,
      explanation: "疑問詞を含む節「～か」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-048",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「経済」は お金や 仕事の 流れのことです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-049",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「都合が 悪い」は 時間が ないことです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-050",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "10時までに 会社に 来なければなりません。",
      answer: true,
      explanation: "義務の「～なければならない」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-051",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "辞書を 見ても いいですか。",
      answer: true,
      explanation: "許可を求める「～てもいい」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-052",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "彼は 日本語を 話すのが 下手です。",
      answer: true,
      explanation: "「～のが下手/上手」の形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-053",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「準備」は 何かを する前に 用意することです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-054",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "回転している機械に 触るときは、軍手（手袋）をする。",
      answer: false,
      explanation: "手袋が巻き込まれて大怪我をするので、基本は素手です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-055",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "避難訓練には、面倒でも 参加しなければならない。",
      answer: true,
      explanation: "いざという時に命を守るために必要です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-056",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "機械を 直すときは、必ず 電源を 切る。",
      answer: true,
      explanation: "突然動き出すと危険です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-057",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 納豆が 食べられます。",
      answer: true,
      explanation: "可能形「食べられる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-058",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "漢字を 書くことが できます。",
      answer: true,
      explanation: "可能表現「～ことができる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-059",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "窓を 開けておきます。",
      answer: true,
      explanation: "準備・放置の状態「～ておく」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-060",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "雨が 降りはじめました。",
      answer: true,
      explanation: "開始を表す「～はじめる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-061",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「急行」は とても ゆっくり走る 電車のことです。",
      answer: false,
      explanation: "急行は「速い」電車のこと。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-062",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「輸出」は 外国へ 物を 売ることです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-063",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "高いところで 作業するときは、安全帯（命綱）をつける。",
      answer: true,
      explanation: "墜落事故を防ぐために必須です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-064",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "小さな怪我は、誰にも 言わなくていい。",
      answer: false,
      explanation: "どんな小さな怪我でも、上司に報告が必要です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-065",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "近くで 火事が 起きたら、大きな声で 周りに 知らせる。",
      answer: true,
      explanation: "「火事だ！」と叫んで周知するのが基本。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-066",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "宿題を 忘れてしまいました。",
      answer: true,
      explanation: "後悔・完了の「～てしまう」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-067",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "弟は 私に お菓子を くれました。",
      answer: true,
      explanation: "授受表現（他人が私にくれる）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-068",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "日本の 食べ物は 高くて おいしいです。",
      answer: true,
      explanation: "い形容詞の連結（くて）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-069",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "彼は 親切で ハンサムです。",
      answer: true,
      explanation: "な形容詞の連結（で）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-070",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「紹介」は 知らない人に 人や 物を 教えることです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-071",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "台車に 荷物を 積みすぎて、前が 見えなくても 大丈夫だ。",
      answer: false,
      explanation: "前が見えないと人とぶつかるので非常に危険です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-072",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "職場の 5Sは、自分だけが やればいい。",
      answer: false,
      explanation: "全員で協力して行うのが5Sです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-073",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "ゴミは 決められた場所に 分けて 捨てる。",
      answer: true,
      explanation: "清掃・清潔の基本です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-074",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "先生に 本を 貸して いただきました。",
      answer: true,
      explanation: "「～てもらう」の謙譲表現。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-075",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "明日は 忙しいから、どこへも 行きません。",
      answer: true,
      explanation: "理由（から）＋全否定（も）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-076",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "部屋が きれいになりました。",
      answer: true,
      explanation: "変化を表す「～になる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-077",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "テレビの 音を 小さくします。",
      answer: true,
      explanation: "変化させる「～くする」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-078",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「景色」は 山や 海などの 眺めのことです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-079",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "カッターを 使うときは、刃を 出しすぎない。",
      answer: true,
      explanation: "刃が折れて飛んでくるのを防ぎます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-080",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "機械の 掃除は、動かしながら やったほうが 速い。",
      answer: false,
      explanation: "巻き込まれる危険があるので、必ず止めてから掃除します。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-081",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "昨日 買ったの 本は これです。",
      answer: false,
      explanation: "名詞修飾のときは「買った本」。「の」は不要。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-082",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "寝る前に、日記を 書きます。",
      answer: true,
      explanation: "前後関係。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-083",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "食べたあとで、皿を 洗います。",
      answer: true,
      explanation: "前後関係。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-084",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「入院」は 病気で 病院に 泊まることです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-085",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "廊下は 走って 移動する。",
      answer: false,
      explanation: "ぶつかって怪我をするので、歩くのがルールです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-086",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "保護メガネは、目が 痛くなってから かける。",
      answer: false,
      explanation: "痛くなる前に、火花やゴミから守るためにかけます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-087",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "工場の ルールは、外国人でも 守らなければならない。",
      answer: true,
      explanation: "全員共通のルールです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-088",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "雪が 降っていますから、寒いです。",
      answer: true,
      explanation: "理由。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-089",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "辞書を 引かずに 読みます。",
      answer: true,
      explanation: "「～ないで」の書き言葉的表現。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-090",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "漢字を 100個 覚えさせられました。",
      answer: true,
      explanation: "使役受身（強制）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-091",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「故障」は 機械が 動かなくなることです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-092",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "休憩時間は、勝手に どこかへ 行ってもいい。",
      answer: false,
      explanation: "職場によりますが、基本は行き先を伝える必要があります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-093",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "道具は 使う前に、壊れていないか 点検する。",
      answer: true,
      explanation: "始業前点検は安全の第一歩です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-094",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "雨が 降りそうです。",
      answer: true,
      explanation: "推測（今にも～しそうだ）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-095",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "毎日 漢字を 練習するように しています。",
      answer: true,
      explanation: "習慣的な努力。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-096",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "窓を 閉めるのを 忘れました。",
      answer: true,
      explanation: "「～のを忘れる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-097",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「修理」は 壊れたものを 直すことです。",
      answer: true,
      explanation: "N4単語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-098",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "体調が 悪いときは、無理をせず 班長に 言う。",
      answer: true,
      explanation: "無理をすると事故の原因になります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-099",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "自分の 担当ではない機械を、勝手に 動かす。",
      answer: false,
      explanation: "事故の元になるので、許可なく動かしてはいけません。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-100",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 田中さんに 褒められました。",
      answer: true,
      explanation: "受身形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-101",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "明日は 雨が 降るでしょう。",
      answer: true,
      explanation: "推量・予想の「～でしょう」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-102",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 漢字を 読むのが できます。",
      answer: false,
      explanation: "正解は「読むことが できます」または「読めます」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-103",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "ここで 写真を 撮らないで ください。",
      answer: true,
      explanation: "依頼・禁止の「～ないでください」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-104",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "昨日は 暑かったです。",
      answer: true,
      explanation: "い形容詞の過去形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-105",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "この 料理は とても 有名でした。",
      answer: true,
      explanation: "な形容詞の過去形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-106",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "工場の 通路で キャッチボールを する。",
      answer: false,
      explanation: "危ないので通路で遊んではいけません。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-107",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "保護具は、自分の サイズに 合ったものを 使う。",
      answer: true,
      explanation: "サイズが合わないと、逆に危険なことがあります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-108",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "機械の 音が いつもと 違うときは、すぐに 止める。",
      answer: true,
      explanation: "異音は故障や事故のサインです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-109",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "掃除を する前に、機械の 電源を 確認する。",
      answer: true,
      explanation: "電源が入ったまま掃除をすると巻き込まれます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-110",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「複雑」な 機械は、直すのが 大変です。",
      answer: true,
      explanation: "N4語彙「複雑」の正しい使い方。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-111",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 先生に 褒められました。",
      answer: true,
      explanation: "受身形（直接受身）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-112",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "雨に 降られて、服が 濡れました。",
      answer: true,
      explanation: "迷惑の受身（間接受身）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-113",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "母は 私に 買い物を させました。",
      answer: true,
      explanation: "使役形（強制・指示）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-114",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 毎日 3キロ 走らされます。",
      answer: true,
      explanation: "使役受身（強制されてやる）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-115",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「反対」は 同じ 意見のことです。",
      answer: false,
      explanation: "反対は「違う」意見、同じは「賛成」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-116",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "この本は 読みやすいです。",
      answer: true,
      explanation: "動作のしやすさを表す「～やすい」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-117",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "このペンは 書きにくいです。",
      answer: true,
      explanation: "動作のしにくさを表す「～にくい」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-118",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "刃物を 渡すときは、刃の方を 相手に 向ける。",
      answer: false,
      explanation: "相手が怪我をしないよう、持ち手の方を向けます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-119",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "火事が 起きたら、エレベーターを 使って 逃げる。",
      answer: false,
      explanation: "閉じ込められる危険があるので、階段を使います。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-120",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "指差呼称は、「目」と「耳」と「手」と「口」を 使う。",
      answer: true,
      explanation: "五感を使って確認の精度を上げます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-121",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "もし お金が あったら、旅行に 行きます。",
      answer: true,
      explanation: "「もし～たら」の仮定。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-122",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "いくら 安くても、買いません。",
      answer: true,
      explanation: "「いくら～ても」の逆接。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-123",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "彼は 日本語を 話せるように なりました。",
      answer: true,
      explanation: "能力の変化を表す「～ようになる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-124",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「厳しい」先生は、あまり 怒りません。",
      answer: false,
      explanation: "厳しい人は、ルールにうるさく、よく怒ります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-125",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「丁寧」に 書いた 字は、読みやすいです。",
      answer: true,
      explanation: "N4語彙「丁寧」の意味。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-126",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "作業台の上は、いつも 整理整頓しておく。",
      answer: true,
      explanation: "5Sの基本です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-127",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "自分の 判断で、安全装置を 外してもよい。",
      answer: false,
      explanation: "勝手に外すと重大な事故に繋がります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-128",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "昨日は 寒かったので、コートを 着ました。",
      answer: true,
      explanation: "理由の「～ので」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-129",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "明日は 休みですから、どこかへ 行きたいです。",
      answer: true,
      explanation: "理由の「～から」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-130",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "彼は 歌が とても 上手です。",
      answer: true,
      explanation: "「～が上手/下手」の形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-131",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "甘いものを 食べすぎて、お腹が 痛いです。",
      answer: true,
      explanation: "過剰の「～すぎる」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-132",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "地震が 起きたら、まずは 机の下に 入る。",
      answer: true,
      explanation: "頭を守るのが最優先です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-133",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "非常ベルが 鳴っても、火が 見えなければ 動かない。",
      answer: false,
      explanation: "音が鳴ったらすぐに避難を開始してください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-134",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "劇物は、鍵がかかる 決まった場所に 保管する。",
      answer: true,
      explanation: "危険な薬などは管理を徹底します。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-135",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「貿易」は 国と 国の 間で 物を 売買することです。",
      answer: true,
      explanation: "N4語彙。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-136",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "窓が 開けて あります。",
      answer: false,
      explanation: "正解は「開けて あります（他動詞）」か「開いています（自動詞）」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-137",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "友達に 借りた本を、もう 返してしまいました。",
      answer: true,
      explanation: "完了の「～てしまう」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-138",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "旅行の前に、切符を 買っておきます。",
      answer: true,
      explanation: "準備の「～ておく」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-139",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「熱心」な 人は、一生懸命 頑張ります。",
      answer: true,
      explanation: "N4語彙。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-140",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「適当」な 説明は、とても 詳しいです。",
      answer: false,
      explanation: "適当は「いい加減」または「ちょうどいい」ことで、詳しくはないです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-141",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "重いものを 持つときは、腰を 高くして 持つ。",
      answer: false,
      explanation: "腰を痛めるので、腰を低くして持ちます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-142",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "フォークリフトの 爪（つめ）の 上に 乗ってはいけない。",
      answer: true,
      explanation: "転落の危険があるため、絶対禁止です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-143",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "休憩が終わったら、すぐに 作業を 始める。",
      answer: true,
      explanation: "時間を守るのも安全管理の一部です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-144",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 田中さんに 本を 貸して あげました。",
      answer: true,
      explanation: "授受表現（私が他人に～してあげる）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-145",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "田中さんは 私に 漢字を 教えて くれました。",
      answer: true,
      explanation: "授受表現（他人が私に～してくれる）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-146",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "日本語を 勉強しに 日本へ 来ました。",
      answer: true,
      explanation: "目的の「～しに（行く/来る）」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-147",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "明日は 雨が 降るかも しれません。",
      answer: true,
      explanation: "可能性の「～かもしれない」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-148",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「用意」は 「準備」と 同じ 意味です。",
      answer: true,
      explanation: "類義語の理解。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-149",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「出発」は 目的地に 着くことです。",
      answer: false,
      explanation: "出発は「出ること」、着くことは「到着」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-150",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "職場の 床に 水が あったら、そのままにする。",
      answer: false,
      explanation: "滑って転ぶので、すぐに拭き取ります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-151",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は パンを 食べながら コーヒーを 飲みます。",
      answer: true,
      explanation: "同時動作「～ながら」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-152",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "辞書を 見ないで 漢字を 書きます。",
      answer: true,
      explanation: "附帯状況「～ないで」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-153",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "テレビが 壊れたので、修理に 出しました。",
      answer: true,
      explanation: "理由。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-154",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "日本語が どんどん 上手に なります。",
      answer: true,
      explanation: "変化の様子。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-155",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "クレーンで 吊り上げている 荷物の 下を 通る。",
      answer: false,
      explanation: "荷物が落ちてくる可能性があるので、絶対に入ってはいけません。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-156",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "自分の 持ち場を 離れるときは、周りの人に 伝える。",
      answer: true,
      explanation: "誰がどこにいるか把握するのが安全の基本です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-157",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私の 趣味は テニスを することです。",
      answer: true,
      explanation: "名詞化「～こと」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-158",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "ここに 座っても かまいませんか。",
      answer: true,
      explanation: "許可の「～てもいい」の少し丁寧な形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-159",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "部屋を きれいに 掃除しました。",
      answer: true,
      explanation: "形容詞の副詞用法。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-160",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「機会」は 「チャンス」と 同じ 意味です。",
      answer: true,
      explanation: "外来語との対応。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-161",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「偶然」は 予定して いたことです。",
      answer: false,
      explanation: "偶然は「予定していなかった」ことです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-162",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "作業中は、携帯電話で 友達と 話してもいい。",
      answer: false,
      explanation: "集中力が切れて事故に繋がります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-163",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "プレス機を 使うときは、必ず 安全柵を 閉める。",
      answer: true,
      explanation: "挟まれ事故を物理的に防ぎます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-164",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "この 漢字は どうやって 読みますか。",
      answer: true,
      explanation: "方法を尋ねる「どうやって」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-165",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 先生に 日本語を 教えて いただきました。",
      answer: true,
      explanation: "謙譲表現（恩恵を受ける）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-166",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "日本語の 本を 10冊 読みました。",
      answer: true,
      explanation: "助数詞（冊）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-167",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "窓から 海が 見えます。",
      answer: true,
      explanation: "可能ではなく、自然に見える「見える」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-168",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「習慣」は いつも している ことです。",
      answer: true,
      explanation: "N4語彙。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-169",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「教育」は 人に 物事を 教えることです。",
      answer: true,
      explanation: "N4語彙。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-170",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "作業服が 破れていたら、すぐに 直すか 替える。",
      answer: true,
      explanation: "破れた部分が機械に引っかかると危険です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-171",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "整理とは、必要なものと 不用なものを 分けて、不用なものを 捨てること。",
      answer: true,
      explanation: "整理の定義です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-172",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "整頓とは、必要なものを 誰でも すぐに 取り出せるように しておくこと。",
      answer: true,
      explanation: "整頓の定義です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-173",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "この お菓子は 100円も します。",
      answer: true,
      explanation: "高いと感じたときの強調「も」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-174",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "テストは 10時までに 終わります。",
      answer: false,
      explanation: "「までに」は期限。「10時に 終わります」が正解。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-175",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 納豆が 食べられます。",
      answer: true,
      explanation: "可能形。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-176",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "ここで 煙草を 吸わないで ください。",
      answer: true,
      explanation: "禁止。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-177",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「故障」は 「壊れる」と 同じ 意味です。",
      answer: true,
      explanation: "類義語。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-178",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「合格」は 試験に 落ちることです。",
      answer: false,
      explanation: "合格は「通る」こと、落ちることは「不合格」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-179",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "溶接作業のときは、遮光面（お面）を 使う。",
      answer: true,
      explanation: "強い光から目を守ります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-180",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "機械の 周りに 燃えやすいものを 置かない。",
      answer: true,
      explanation: "火災を防止します。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-181",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "旅行に 行くか どうか、まだ 決めていません。",
      answer: true,
      explanation: "「～かどうか」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-182",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "田中さんは パーティーに 来ると 言っていました。",
      answer: true,
      explanation: "引用「～と言っていた」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-183",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "図書館へ 本を 返しに 行きます。",
      answer: true,
      explanation: "目的「～に（行く）」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-184",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "1時間 待ちましたが、誰も 来ませんでした。",
      answer: true,
      explanation: "全否定「誰も～ない」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-185",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「最近」は ずっと 昔のことです。",
      answer: false,
      explanation: "最近は「少し前（近ごろ）」のことです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-186",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「将来」は 夢を 叶えたい 時間のことです。",
      answer: true,
      explanation: "未来のニュアンス。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-187",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "保護靴は、足の上に 重いものが 落ちても 大丈夫なように なっている。",
      answer: true,
      explanation: "つま先に鉄板などが入っています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-188",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "薬品が 目に 入ったら、すぐに 大量の水で 洗う。",
      answer: true,
      explanation: "応急処置として非常に重要です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-189",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "自分の 失敗を 隠して、報告しない。",
      answer: false,
      explanation: "小さな隠し事が大きな事故を招きます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-190",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 母に 買い物を 頼まれました。",
      answer: true,
      explanation: "受身形（依頼）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-191",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "彼は とても 忙しそうです。",
      answer: true,
      explanation: "推測の「～そうだ」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-192",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "この ケーキは おいしくないそうです。",
      answer: true,
      explanation: "伝聞の「～そうだ（ない形＋そうだ）」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-193",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「中止」は 予定を 変えずに やることです。",
      answer: false,
      explanation: "中止は「やめる」ことです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-194",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "「反対」は 右の ほうのことです。",
      answer: false,
      explanation: "それは「右の反対（左）」、または「反対側」の意味です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-195",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "階段を 上り下りするときは、手すりを 持つ。",
      answer: true,
      explanation: "転倒防止の基本です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-196",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "朝礼（ちょうれい）は、その日の 作業を 確認する 大事な時間だ。",
      answer: true,
      explanation: "現場のコミュニケーションの基本です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-197",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "私は 毎日 漢字を 覚えるように しています。",
      answer: true,
      explanation: "継続的な努力。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-198",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "昨日は どこへも 行きませんでした。",
      answer: true,
      explanation: "全否定。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-199",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "田中さんに 本を 貸して もらいました。",
      answer: true,
      explanation: "授受（恩恵）。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "fj-n4-j-200",
      kind: "flash-judge",
      sectionId: "bunpo",
      prompt: "ここで 靴を 脱がなければ なりません。",
      answer: true,
      explanation: "義務。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },

  ],
}

export function getFlashJudgePool(quizType: QuizType) {
  const list = flashJudgePools[quizType] ?? []
  return list.filter((q) => q.enabled)
}
