// app/(auth)/game/pools/memoryBurstPools.ts
import type { QuizType } from "@/app/data/types"
import type { MemoryBurstQuestion } from "../types"

export const memoryBurstPools: Partial<Record<QuizType, MemoryBurstQuestion[]>> = {
  "japanese-n4": [
    
    // ✅ 読解・会話（Memory Burst / N4）
    {
      id: "mb-n4-001",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日は朝7時に駅で友だちと会います。",
      question: "何時に会いますか？",
      choices: ["6時", "7時", "8時", "9時"],
      correctIndex: 1,
      explanation: "「朝7時に」と書いてあります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-002",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日は雨でしたが、今日はとてもいい天気です。",
      question: "今日の天気はどうですか？",
      choices: ["雨", "雪", "くもり", "晴れ"],
      correctIndex: 3,
      explanation: "「いい天気」は晴れのことです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-003",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは毎日30分漢字を練習しています。",
      question: "何を練習していますか？",
      choices: ["数学", "英語", "漢字", "料理"],
      correctIndex: 2,
      explanation: "「漢字を練習して」います。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-004",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この薬は1日に3回、ご飯を食べたあとに飲んでください。",
      question: "薬はいつ飲みますか？",
      choices: ["寝る前", "食べる前", "食べたあと", "いつでも"],
      correctIndex: 2,
      explanation: "「食べたあとに」飲みます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-005",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私はりんごよりバナナのほうが好きです。",
      question: "何が一番好きですか？",
      choices: ["りんご", "バナナ", "みかん", "ぶどう"],
      correctIndex: 1,
      explanation: "「バナナのほうが好き」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-006",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "図書館は毎週月曜日が休みです。",
      question: "いつ休みですか？",
      choices: ["火曜日", "土曜日", "日曜日", "月曜日"],
      correctIndex: 3,
      explanation: "「月曜日が休み」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-007",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "兄は銀行で働いていますが、弟は大学生です。",
      question: "弟は何をしていますか？",
      choices: ["銀行員", "学生", "先生", "医者"],
      correctIndex: 1,
      explanation: "「弟は大学生」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-008",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "冷蔵庫の中に牛乳が2本と卵が6個あります。",
      question: "卵はいくつありますか？",
      choices: ["2個", "4個", "6個", "8個"],
      correctIndex: 2,
      explanation: "「卵が6個」あります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-009",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "駅から会社まで歩いて15分かかります。",
      question: "会社までどうやって行きますか？",
      choices: ["バス", "電車", "車", "徒歩"],
      correctIndex: 3,
      explanation: "「歩いて」行くのは徒歩です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-010",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日のパーティーは18時半から始まります。",
      question: "何時に始まりますか？",
      choices: ["6時", "6時半", "8時", "8時半"],
      correctIndex: 1,
      explanation: "「18時半」は午後6時半です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-011",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "会議室の机の上に黒いカバンが置いてあります。",
      question: "カバンはどこにありますか？",
      choices: ["椅子の上", "机の下", "机の上", "棚の中"],
      correctIndex: 2,
      explanation: "「机の上に」あります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-012",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎週水曜日と土曜日にジムへ行きます。",
      question: "1週間に何回ジムへ行きますか？",
      choices: ["1回", "2回", "3回", "4回"],
      correctIndex: 1,
      explanation: "水曜と土曜で「2回」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-013",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "日本語の授業は10時に始まり、12時に終わります。",
      question: "授業は何時間ありますか？",
      choices: ["1時間", "2時間", "3時間", "4時間"],
      correctIndex: 1,
      explanation: "10時〜12時は「2時間」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-014",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "暑いので窓を開けて、エアコンを消しました。",
      question: "エアコンはどうなっていますか？",
      choices: ["ついている", "壊れている", "消えている", "動いている"],
      correctIndex: 2,
      explanation: "「エアコンを消しました」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-015",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日は10時に寝ましたが、今日は11時に寝ます。",
      question: "今日は何時に寝ますか？",
      choices: ["9時", "10時", "11時", "12時"],
      correctIndex: 2,
      explanation: "「今日は11時に」寝ます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-016",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "佐藤さんはテニスが上手ですが、サッカーは下手です。",
      question: "佐藤さんは何が上手ですか？",
      choices: ["サッカー", "ピアノ", "テニス", "料理"],
      correctIndex: 2,
      explanation: "「テニスが上手」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-017",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "傘を忘れたので、友だちに貸してもらいました。",
      question: "誰の傘を使っていますか？",
      choices: ["自分の", "友だちの", "先生の", "母の"],
      correctIndex: 1,
      explanation: "「友だちに借りた」傘です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-018",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "映画は大人1800円、子ども900円です。",
      question: "子どもはいくらですか？",
      choices: ["1800円", "1000円", "900円", "無料"],
      correctIndex: 2,
      explanation: "「子ども900円」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-019",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "工場の入口でヘルメットをかぶってください。",
      question: "どこでかぶりますか？",
      choices: ["事務所", "入口", "食堂", "駐車場"],
      correctIndex: 1,
      explanation: "「入口で」かぶります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-020",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この料理は肉を使わずに、野菜だけで作りました。",
      question: "何を使いましたか？",
      choices: ["肉", "魚", "野菜", "卵"],
      correctIndex: 2,
      explanation: "「野菜だけで」作りました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-021",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "郵便局へ行ってから、スーパーへ行きます。",
      question: "最初はどこへ行きますか？",
      choices: ["スーパー", "銀行", "家", "郵便局"],
      correctIndex: 3,
      explanation: "「郵便局へ行ってから」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-022",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は去年日本へ来ました。今は2年目です。",
      question: "日本へ来たのはいつですか？",
      choices: ["先月", "半年前", "去年", "おととし"],
      correctIndex: 2,
      explanation: "「去年」来ました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-023",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "砂糖を入れますか？いいえ、結構です。",
      question: "コーヒーはどうしますか？",
      choices: ["砂糖を入れる", "砂糖を入れない", "ミルクを入れる", "飲まない"],
      correctIndex: 1,
      explanation: "「結構です」は不要の意味です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-024",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この本は読みやすくて、とてもおもしろいです。",
      question: "本はどうですか？",
      choices: ["難しい", "おもしろい", "つまらない", "長い"],
      correctIndex: 1,
      explanation: "「とてもおもしろい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-025",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "故障しているので階段を使いましょう。",
      question: "どうして階段を使いますか？",
      choices: ["運動", "故障しているから", "近い", "好き"],
      correctIndex: 1,
      explanation: "「故障している」からです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-026",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "1階は駐車場で、2階が受付です。",
      question: "受付はどこですか？",
      choices: ["1階", "2階", "3階", "外"],
      correctIndex: 1,
      explanation: "「2階が受付」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-027",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日の持ち物は筆記用具とお弁当です。",
      question: "何を持って行きますか？",
      choices: ["辞書", "飲み物", "お弁当", "カメラ"],
      correctIndex: 2,
      explanation: "「お弁当」が必要です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-028",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "お酒が飲めませんから、お茶をください。",
      question: "何を飲みますか？",
      choices: ["ビール", "ワイン", "お茶", "水"],
      correctIndex: 2,
      explanation: "「お茶をください」と言っています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-029",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "漢字のテストは全部で20問あります。",
      question: "テストは何問ですか？",
      choices: ["10問", "15問", "20問", "30問"],
      correctIndex: 2,
      explanation: "「全部で20問」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-030",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "誕生日に兄から時計をもらいました。",
      question: "誰が時計をくれましたか？",
      choices: ["父", "母", "兄", "弟"],
      correctIndex: 2,
      explanation: "「兄から」もらいました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-031",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここは禁煙ですから、吸わないでください。",
      question: "ここで吸ってもいいですか？",
      choices: ["はい", "いいえ", "外ならいい", "少しなら"],
      correctIndex: 1,
      explanation: "禁煙は「ダメ」という意味です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-032",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "会社は8時45分に始まります。",
      question: "何分に始まりますか？",
      choices: ["15分", "30分", "45分", "0分"],
      correctIndex: 2,
      explanation: "「45分」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-033",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "白シャツ2枚と青シャツ1枚買いました。",
      question: "全部で何枚買いましたか？",
      choices: ["1枚", "2枚", "3枚", "4枚"],
      correctIndex: 2,
      explanation: "2 ＋ 1 ＝ 3枚です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-034",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "辞書を忘れたので先生に借りました。",
      question: "誰に借りましたか？",
      choices: ["友だち", "先生", "隣の人", "家族"],
      correctIndex: 1,
      explanation: "「先生に借りました」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-035",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "趣味は映画を見ることと、泳ぐことです。",
      question: "趣味は何ですか？",
      choices: ["料理", "読書", "水泳", "ピアノ"],
      correctIndex: 2,
      explanation: "「泳ぐこと」は水泳です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-036",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "窓のそばに花びんがあります。",
      question: "花びんはどこですか？",
      choices: ["窓のそば", "机の上", "ドア前", "外"],
      correctIndex: 0,
      explanation: "「窓のそば」にあります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-037",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "お腹が痛いので病院へ行きます。",
      question: "どうして病院へ行きますか？",
      choices: ["頭痛", "風邪", "腹痛", "足が痛い"],
      correctIndex: 2,
      explanation: "「お腹が痛い」からです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-038",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "赤いペンで名前を書いてください。",
      question: "何色で書きますか？",
      choices: ["黒", "青", "赤", "緑"],
      correctIndex: 2,
      explanation: "「赤いペン」を指定しています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-039",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このズボンは私には少し短いです。",
      question: "ズボンはどうですか？",
      choices: ["長い", "短い", "ちょうどいい", "大きい"],
      correctIndex: 1,
      explanation: "「少し短い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-040",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "料理は自分たちで作りました。",
      question: "料理はどうしましたか？",
      choices: ["買った", "店で食べた", "もらった", "作った"],
      correctIndex: 3,
      explanation: "「自分たちで作った」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-041",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "バスが遅れたので、10分待ちました。",
      question: "何分待ちましたか？",
      choices: ["5分", "10分", "15分", "20分"],
      correctIndex: 1,
      explanation: "「10分待ちました」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-042",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎日寝る前に日記を書きます。",
      question: "いつ日記を書きますか？",
      choices: ["朝", "昼休み", "夕食後", "寝る前"],
      correctIndex: 3,
      explanation: "「寝る前に」書きます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-043",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "スーパーの隣にコンビニがあります。",
      question: "コンビニはどこですか？",
      choices: ["駅の中", "公園前", "スーパー隣", "病院裏"],
      correctIndex: 2,
      explanation: "「スーパーの隣」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-044",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "今日の会議には12人が出席します。",
      question: "何人来ますか？",
      choices: ["10人", "11人", "12人", "13人"],
      correctIndex: 2,
      explanation: "「12人が出席」します。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-045",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "犬が好きですが、猫は嫌いです。",
      question: "何が嫌いですか？",
      choices: ["犬", "猫", "鳥", "魚"],
      correctIndex: 1,
      explanation: "「猫は嫌い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-046",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "先生は今、事務所にいます。",
      question: "先生はどこにいますか？",
      choices: ["教室", "事務所", "食堂", "図書館"],
      correctIndex: 1,
      explanation: "「事務所に」います。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-047",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "テストの時間は60分です。",
      question: "何分間ですか？",
      choices: ["30分", "45分", "60分", "90分"],
      correctIndex: 2,
      explanation: "「60分」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-048",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "靴を脱いでから部屋に入ってください。",
      question: "入る前に何をしますか？",
      choices: ["手を洗う", "靴を脱ぐ", "挨拶", "開窓"],
      correctIndex: 1,
      explanation: "「靴を脱いでから」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-049",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日は雪が降るそうですよ。",
      question: "明日の天気は何ですか？",
      choices: ["雨", "晴れ", "雪", "くもり"],
      correctIndex: 2,
      explanation: "「雪」の予報です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-050",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎日卵を1個食べます。",
      question: "1週間にいくつ食べますか？",
      choices: ["1個", "5個", "7個", "10個"],
      correctIndex: 2,
      explanation: "1日1個 × 7日 ＝ 7個です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-051",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このバスは空港には行きません。",
      question: "どこへ行きませんか？",
      choices: ["駅", "病院", "空港", "公園"],
      correctIndex: 2,
      explanation: "「空港には行かない」と書いてあります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-052",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "来週の日曜日は父の誕生日です。",
      question: "お父さんの誕生日はいつですか？",
      choices: ["今日", "明日", "来週の日曜日", "土曜日"],
      correctIndex: 2,
      explanation: "「来週の日曜日」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-053",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は字が小さすぎて読めませんでした。",
      question: "どうして読めませんでしたか？",
      choices: ["漢字が難しい", "字が小さい", "字が下手", "暗い"],
      correctIndex: 1,
      explanation: "「字が小さすぎて」が原因です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-054",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "カバンの中に鍵を入れたまま閉めました。",
      question: "鍵はどこにありますか？",
      choices: ["ポケット", "机の上", "カバンの中", "玄関"],
      correctIndex: 2,
      explanation: "「カバンの中」に入れたままです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-055",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは英語だけでなくスペイン語も話せます。",
      question: "田中さんは何語が話せますか？",
      choices: ["英語だけ", "中国語", "英語とスペイン語", "日本語"],
      correctIndex: 2,
      explanation: "英語とスペイン語の2つです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-056",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "風邪をひいたので今日は学校を休みます。",
      question: "今日、学校へ行きますか？",
      choices: ["行く", "行かない", "午後から行く", "走る"],
      correctIndex: 1,
      explanation: "「休みます」は行かないという意味です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-057",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "公園の掃除は9時から11時までです。",
      question: "掃除は何時間しますか？",
      choices: ["1時間", "2時間", "3時間", "4時間"],
      correctIndex: 1,
      explanation: "9時〜11時は「2時間」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-058",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この映画はあまりおもしろくなかった。",
      question: "映画はどうでしたか？",
      choices: ["おもしろい", "まあまあ", "つまらない", "怖い"],
      correctIndex: 2,
      explanation: "「おもしろくない」＝つまらない。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-059",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "電車の中で携帯電話を使わないでください。",
      question: "どこで使ってはいけませんか？",
      choices: ["駅", "家", "電車の中", "会社"],
      correctIndex: 2,
      explanation: "「電車の中」のルールです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-060",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私はコーヒーよりお茶のほうが好きです。",
      question: "何が好きですか？",
      choices: ["コーヒー", "お茶", "水", "ジュース"],
      correctIndex: 1,
      explanation: "「お茶のほうが好き」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-061",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日は早く起きなければなりません。",
      question: "明日はどうしますか？",
      choices: ["ゆっくり寝る", "早く起きる", "休む", "買い物"],
      correctIndex: 1,
      explanation: "「早く起きなければならない」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-062",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このカメラは高かったですが、とてもいいです。",
      question: "カメラについてどう思いますか？",
      choices: ["安くていい", "高くて悪い", "高くていい", "安い"],
      correctIndex: 2,
      explanation: "「高かったが、とてもいい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-063",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日はどこへも行きませんでした。",
      question: "昨日は何をしましたか？",
      choices: ["買い物", "旅行", "家にいた", "学校"],
      correctIndex: 2,
      explanation: "どこへも行かない＝家にいた。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-064",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは料理が上手で、よく作ってくれます。",
      question: "何が得意ですか？",
      choices: ["掃除", "洗濯", "料理", "運転"],
      correctIndex: 2,
      explanation: "「料理が上手」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-065",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "暑いので冷たい飲み物が飲みたいです。",
      question: "何が飲みたいですか？",
      choices: ["熱い茶", "冷たい飲み物", "お菓子", "ミルク"],
      correctIndex: 1,
      explanation: "「冷たい飲み物」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-066",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎朝パンと卵を食べます。",
      question: "いつ食べますか？",
      choices: ["朝", "昼", "夜", "寝る前"],
      correctIndex: 0,
      explanation: "「毎朝」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-067",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "3階に事務所と会議室があります。",
      question: "会議室はどこですか？",
      choices: ["1階", "2階", "3階", "4階"],
      correctIndex: 2,
      explanation: "「3階」にあります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-068",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この仕事は1人で1時間かかります。",
      question: "2人でやったら何分ですか？",
      choices: ["30分", "60分", "90分", "120分"],
      correctIndex: 0,
      explanation: "1人で60分なら、2人なら30分です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-069",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "窓から海が見えます。",
      question: "何が見えますか？",
      choices: ["山", "空", "海", "花"],
      correctIndex: 2,
      explanation: "「海」が見えます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-070",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この店は安くておいしいので有名です。",
      question: "どうして有名ですか？",
      choices: ["高いから", "遠いから", "安くておいしい", "広い"],
      correctIndex: 2,
      explanation: "「安くておいしい」からです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-071",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私はピアノを5歳から習っています。",
      question: "いつから習っていますか？",
      choices: ["3歳", "5歳", "10歳", "去年"],
      correctIndex: 1,
      explanation: "「5歳から」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-072",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日の朝礼は8時10分に集まってください。",
      question: "何時に集まりますか？",
      choices: ["8時", "8時10分", "8時半", "9時"],
      correctIndex: 1,
      explanation: "「8時10分」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-073",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このペンはインクがないので書けません。",
      question: "どうして書けませんか？",
      choices: ["故障", "インクがない", "紙が悪い", "重い"],
      correctIndex: 1,
      explanation: "インクがないからです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-074",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は1ヶ月に2回実家に帰ります。",
      question: "1年に何回帰りますか？",
      choices: ["12回", "20回", "24回", "30回"],
      correctIndex: 2,
      explanation: "月2回 × 12ヶ月 ＝ 24回です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-075",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "教室に先生と学生が5人います。",
      question: "全部で何人いますか？",
      choices: ["1人", "5人", "6人", "4人"],
      correctIndex: 2,
      explanation: "先生(1) ＋ 学生(5) ＝ 6人。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-076",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このズボンは青いですが、シャツは白いです。",
      question: "シャツは何色ですか？",
      choices: ["青", "赤", "白", "黒"],
      correctIndex: 2,
      explanation: "「シャツは白い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-077",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "佐藤さんは昨日休みでしたが、今日は来ます。",
      question: "佐藤さんは今日来ますか？",
      choices: ["来る", "来ない", "遅れて来る", "休み"],
      correctIndex: 0,
      explanation: "「今日は来ます」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-078",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここで写真を撮ってもいいですか。",
      question: "何を聞いていますか？",
      choices: ["場所", "時間", "許可", "名前"],
      correctIndex: 2,
      explanation: "「〜てもいいですか」は許可です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-079",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "電車は20分に1本来ます。",
      question: "1時間に何本来ますか？",
      choices: ["1本", "2本", "3本", "4本"],
      correctIndex: 2,
      explanation: "60分の中に20分は3回あります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-080",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は弟が2人と妹が1人います。",
      question: "きょうだいは自分を含めて何人？",
      choices: ["2人", "3人", "4人", "5人"],
      correctIndex: 2,
      explanation: "自分＋弟2人＋妹1人＝4人。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-081",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "牛肉を300グラム買いました。",
      question: "何を買いましたか？",
      choices: ["豚肉", "鳥肉", "牛肉", "魚"],
      correctIndex: 2,
      explanation: "「牛肉」を買いました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-082",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このカバンは軽くて丈夫です。",
      question: "カバンはどうですか？",
      choices: ["重い", "弱い", "軽くて丈夫", "高い"],
      correctIndex: 2,
      explanation: "「軽くて丈夫」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-083",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "雨が降ってきましたが、傘を持っていません。",
      question: "どんな状況ですか？",
      choices: ["傘がある", "困っている", "家にいる", "晴れ"],
      correctIndex: 1,
      explanation: "傘がなくて困っています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-084",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "わたしの誕生日は5月5日です。",
      question: "誕生日はいつですか？",
      choices: ["1月1日", "3月3日", "5月5日", "12月"],
      correctIndex: 2,
      explanation: "「5月5日」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-085",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "靴をはきかえてから工場に入ってください。",
      question: "入る前に何をしますか？",
      choices: ["脱ぐ", "靴をはきかえる", "手を洗う", "寝る"],
      correctIndex: 1,
      explanation: "「はきかえてから」入ります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-086",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ジュースはよく振ってから飲んでください。",
      question: "飲む前に何をしますか？",
      choices: ["温める", "冷やす", "振る", "混ぜる"],
      correctIndex: 2,
      explanation: "「振ってから」飲みます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-087",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎日1時間漢字を練習します。",
      question: "1週間に何時間しますか？",
      choices: ["1時間", "5時間", "7時間", "10時間"],
      correctIndex: 2,
      explanation: "1日1時間 × 7日 ＝ 7時間。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-088",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "集合場所は公園の正門前です。",
      question: "どこに集まりますか？",
      choices: ["駅", "学校", "公園の正門前", "家"],
      correctIndex: 2,
      explanation: "「公園の正門前」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-089",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この機械は水をかけてはいけません。",
      question: "何をしてはいけませんか？",
      choices: ["掃除", "使う", "水をかける", "見る"],
      correctIndex: 2,
      explanation: "水をかけてはいけません。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-090",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "図書館で本を3冊借りました。",
      question: "何冊借りましたか？",
      choices: ["1冊", "2冊", "3冊", "4冊"],
      correctIndex: 2,
      explanation: "「3冊」借りました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-091",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "今日の昼ごはんはパンとサラダでした。",
      question: "何を食べましたか？",
      choices: ["麺", "パンとサラダ", "ご飯", "肉"],
      correctIndex: 1,
      explanation: "「パンとサラダ」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-092",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここから駅までバスで30分です。",
      question: "何で行きますか？",
      choices: ["電車", "歩き", "バス", "タクシー"],
      correctIndex: 2,
      explanation: "「バスで」行きます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-093",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "甘いものは好きですが、辛いものは嫌いです。",
      question: "何が嫌いですか？",
      choices: ["ケーキ", "辛いもの", "果物", "アイス"],
      correctIndex: 1,
      explanation: "「辛いものは嫌い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-094",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは今電話をしています。",
      question: "何をしていますか？",
      choices: ["読書", "電話", "睡眠", "勉強"],
      correctIndex: 1,
      explanation: "「電話をしています」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-095",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この本は昨日読み終わりました。",
      question: "いつ読みましたか？",
      choices: ["今日", "明日", "去年", "昨日"],
      correctIndex: 3,
      explanation: "「昨日」読み終わりました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-096",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "電灯が消えているので、暗いです。",
      question: "どうして暗いですか？",
      choices: ["窓がない", "夜", "電灯が消えている", "冬"],
      correctIndex: 2,
      explanation: "電灯が消えているからです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-097",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "兄は背が高いですが、弟は低いです。",
      question: "だれが背が低いですか？",
      choices: ["父", "兄", "弟", "母"],
      correctIndex: 2,
      explanation: "「弟は低い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-098",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎日2リットル水を飲みます。",
      question: "何を飲みますか？",
      choices: ["茶", "ジュース", "水", "牛乳"],
      correctIndex: 2,
      explanation: "「水」を飲みます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-099",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここで吸ってもいいですか。いいえ、だめです。",
      question: "吸えますか？",
      choices: ["はい", "いいえ", "外なら", "少し"],
      correctIndex: 1,
      explanation: "「いいえ、だめです」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-100",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "10月は休みがたくさんあります。",
      question: "休みはどうですか？",
      choices: ["少ない", "ない", "たくさんある", "毎週"],
      correctIndex: 2,
      explanation: "「たくさん」あります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-101",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日は忙しくて、テレビを見ませんでした。",
      question: "昨日はどうでしたか？",
      choices: ["暇だった", "テレビを見た", "忙しかった", "寝ていた"],
      correctIndex: 2,
      explanation: "「忙しくて」と理由を言っています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-102",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私はいつも12時に寝て、7時に起きます。",
      question: "何時間寝ますか？",
      choices: ["5時間", "6時間", "7時間", "8時間"],
      correctIndex: 2,
      explanation: "12時から7時までは「7時間」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-103",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは眼鏡をかけていないと、字が見えません。",
      question: "字を見るために何が必要ですか？",
      choices: ["帽子", "眼鏡", "時計", "辞書"],
      correctIndex: 1,
      explanation: "「眼鏡をかけていないと見えない」＝眼鏡が必要です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-104",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "公園の池には、魚がたくさん泳いでいます。",
      question: "池に何がいますか？",
      choices: ["鳥", "犬", "魚", "猫"],
      correctIndex: 2,
      explanation: "「魚がたくさん泳いでいる」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-105",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "日本では12月に雪が降ることがあります。",
      question: "いつ雪が降りますか？",
      choices: ["4月", "8月", "10月", "12月"],
      correctIndex: 3,
      explanation: "「12月に」と書いてあります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-106",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この部屋は禁煙ですが、外に喫煙所があります。",
      question: "どこでタバコを吸えますか？",
      choices: ["部屋の中", "トイレ", "外の喫煙所", "どこでも"],
      correctIndex: 2,
      explanation: "「外に喫煙所がある」のでそこなら吸えます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-107",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "雨が降っているので、タクシーで行きましょう。",
      question: "どうやって行きますか？",
      choices: ["バス", "電車", "歩き", "タクシー"],
      correctIndex: 3,
      explanation: "「タクシーで行こう」と提案しています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-108",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "冷蔵庫の中には、水とビールしかありません。",
      question: "お茶はありますか？",
      choices: ["たくさんある", "少しある", "ない", "もうすぐ来る"],
      correctIndex: 2,
      explanation: "「水とビールしか」ないので、お茶はありません。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-109",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は日本のアニメが見たくて、日本語を勉強しています。",
      question: "どうして勉強していますか？",
      choices: ["仕事のため", "アニメのため", "旅行のため", "暇だから"],
      correctIndex: 1,
      explanation: "「アニメが見たくて」が理由です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-110",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "エレベーターが動かないので、4階まで歩きました。",
      question: "どうやって4階へ行きましたか？",
      choices: ["車", "エレベーター", "エスカレーター", "階段（歩き）"],
      correctIndex: 3,
      explanation: "エレベーターが動かないので「歩いた」＝階段です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-111",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "兄は医者で、父は学校の先生です。",
      question: "お父さんの仕事は何ですか？",
      choices: ["医者", "警察官", "先生", "学生"],
      correctIndex: 2,
      explanation: "「父は学校の先生」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-112",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "毎日100円ずつ貯金しています。",
      question: "10日でいくらになりますか？",
      choices: ["100円", "500円", "1000円", "10000円"],
      correctIndex: 2,
      explanation: "100円 × 10日 ＝ 1000円です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-113",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私の家から駅まで、自転車で10分です。",
      question: "駅まで何で行きますか？",
      choices: ["徒歩", "バス", "車", "自転車"],
      correctIndex: 3,
      explanation: "「自転車で」行きます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-114",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "レストランを予約しておきました。",
      question: "今、レストランはどうなっていますか？",
      choices: ["満員", "休み", "予約済み", "工事中"],
      correctIndex: 2,
      explanation: "「予約しておいた」ので予約されています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-115",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日はお酒を飲みすぎたので、頭が痛いです。",
      question: "今、どうして頭が痛いのですか？",
      choices: ["風邪", "勉強しすぎ", "酒の飲みすぎ", "寝不足"],
      correctIndex: 2,
      explanation: "「お酒を飲みすぎた」のが原因です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-116",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "山の上はとても寒かったです。",
      question: "山の下はどうでしたか？",
      choices: ["寒かった", "暑かった", "雪だった", "わからない"],
      correctIndex: 3,
      explanation: "山の上の話しかしていないので、下は不明です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-117",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "図書館で借りた本を、明日返さなければなりません。",
      question: "明日何をしますか？",
      choices: ["本を買う", "本を借りる", "本を返す", "本を捨てる"],
      correctIndex: 2,
      explanation: "「明日返さなければならない」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-118",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この料理は少し辛いですが、とても美味しいです。",
      question: "味はどうですか？",
      choices: ["甘い", "苦い", "辛くて美味しい", "まずい"],
      correctIndex: 2,
      explanation: "「少し辛いが、とても美味しい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-119",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは昨日、会社を休みました。",
      question: "田中さんは昨日、どこにいましたか？",
      choices: ["会社", "病院", "家など会社以外", "学校"],
      correctIndex: 2,
      explanation: "会社を休んだので、会社以外の場所にいました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-120",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎週日曜日に、部屋を掃除します。",
      question: "1ヶ月に何回掃除しますか？",
      choices: ["1回", "2回", "4回", "7回"],
      correctIndex: 2,
      explanation: "日曜は週に1回なので、1ヶ月（4週）で4回です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-121",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "お金がないので、何も買えません。",
      question: "何か買いますか？",
      choices: ["たくさん買う", "少し買う", "何も買わない", "明日買う"],
      correctIndex: 2,
      explanation: "「何も買えない」状況です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-122",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "弟はテニスが下手ですが、大好きです。",
      question: "弟はテニスについてどう思っていますか？",
      choices: ["嫌い", "好き", "やりたくない", "怖い"],
      correctIndex: 1,
      explanation: "下手ですが「大好き」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-123",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここに住所を書いて、名前を教えないでください。",
      question: "何を書きますか？",
      choices: ["名前", "住所", "電話番号", "年齢"],
      correctIndex: 1,
      explanation: "「住所を書いて」と指示されています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-124",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "コーヒーと紅茶、どちらがいいですか。紅茶をください。",
      question: "何を飲みますか？",
      choices: ["コーヒー", "お茶", "紅茶", "ジュース"],
      correctIndex: 2,
      explanation: "「紅茶をください」と答えています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-125",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "夏休みは、北海道へ行こうと思っています。",
      question: "どこへ行く予定ですか？",
      choices: ["沖縄", "東京", "北海道", "海外"],
      correctIndex: 2,
      explanation: "「北海道へ行こう」と思っています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-126",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この仕事は、明日までに終わらせてください。",
      question: "いつまでに終わらせますか？",
      choices: ["今日中", "明日中", "明後日", "来週"],
      correctIndex: 1,
      explanation: "「明日まで」の期限です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-127",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "公園の真ん中に、大きな木があります。",
      question: "木はどこにありますか？",
      choices: ["公園の入口", "公園の隅", "公園の真ん中", "外"],
      correctIndex: 2,
      explanation: "「公園の真ん中に」あります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-128",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "映画が始まる前に、ポップコーンを買いました。",
      question: "いつ買いましたか？",
      choices: ["映画中", "映画が終わった後", "映画が始まる前", "昨日"],
      correctIndex: 2,
      explanation: "「始まる前に」買いました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-129",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は背が高いですが、姉はもっと高いです。",
      question: "誰が一番背が高いですか？",
      choices: ["私", "姉", "父", "母"],
      correctIndex: 1,
      explanation: "私より「姉のほうがもっと高い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-130",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このバスは、10時ちょうどに出発します。",
      question: "何時に出ますか？",
      choices: ["9時50分", "10時0分", "10時10分", "11時"],
      correctIndex: 1,
      explanation: "「10時ちょうど」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-131",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "部屋の電気をつけたまま、寝てしまいました。",
      question: "起きた時、電気はどうなっていましたか？",
      choices: ["消えていた", "ついていた", "壊れていた", "暗かった"],
      correctIndex: 1,
      explanation: "「つけたまま」寝たので、ついていました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-132",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "病院は駅から歩いて20分、バスで5分です。",
      question: "バスで行くと何分ですか？",
      choices: ["5分", "10分", "15分", "20分"],
      correctIndex: 0,
      explanation: "「バスで5分」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-133",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "今日は財布を忘れたので、パンを1つしか買えませんでした。",
      question: "何を買いましたか？",
      choices: ["お弁当", "お菓子", "飲み物", "パン"],
      correctIndex: 3,
      explanation: "「パンを1つ」買いました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-134",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "佐藤さんは歌を歌うのがとても上手です。",
      question: "佐藤さんの得意なことは何ですか？",
      choices: ["ダンス", "料理", "歌", "ピアノ"],
      correctIndex: 2,
      explanation: "「歌を歌うのが上手」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-135",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここで靴を脱いで、スリッパをはいてください。",
      question: "部屋の中で何をはきますか？",
      choices: ["靴", "靴下", "サンダル", "スリッパ"],
      correctIndex: 3,
      explanation: "「スリッパをはいて」ください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-136",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "試験中は辞書を使ってもいいですが、スマホはだめです。",
      question: "何を使ってもいいですか？",
      choices: ["スマホ", "辞書", "教科書", "何もだめ"],
      correctIndex: 1,
      explanation: "「辞書を使ってもいい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-137",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎日、会社で12時から1時まで昼休みをとります。",
      question: "昼休みは何時間ですか？",
      choices: ["30分", "1時間", "2時間", "決まっていない"],
      correctIndex: 1,
      explanation: "12時から1時までは「1時間」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-138",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日の天気は「晴れのち雨」です。",
      question: "午後から雨が降るかもしれません。",
      choices: ["はい", "いいえ", "わからない", "ずっと晴れ"],
      correctIndex: 0,
      explanation: "「のち雨」は後から雨という意味なので「はい」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-139",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このズボンは少しきついので、もっと大きいのはありませんか？",
      question: "今のズボンはどうですか？",
      choices: ["ゆるい", "小さい（きつい）", "長い", "ちょうどいい"],
      correctIndex: 1,
      explanation: "「きつい」＝今のサイズが小さい。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-140",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "窓の外に鳥が3羽います。",
      question: "鳥は何羽いますか？",
      choices: ["1羽", "2羽", "3羽", "4羽"],
      correctIndex: 2,
      explanation: "「3羽」います。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-141",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は犬も好きですが、猫のほうがもっと好きです。",
      question: "何が一番好きですか？",
      choices: ["犬", "猫", "鳥", "魚"],
      correctIndex: 1,
      explanation: "犬より「猫のほうが好き」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-142",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "会社は土曜日も日曜日も休みではありません。",
      question: "休みはいつですか？",
      choices: ["土日", "土曜だけ", "日曜だけ", "土日以外"],
      correctIndex: 3,
      explanation: "土日も休み「ではない」＝それ以外が休みです。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-143",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "晩ご飯を食べた後で、薬を飲んでください。",
      question: "いつ薬を飲みますか？",
      choices: ["食前", "食中", "食後", "寝る前"],
      correctIndex: 2,
      explanation: "「食べた後」＝食後です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-144",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "漢字は難しいですが、書くのはおもしろいです。",
      question: "漢字を書くことについてどう思っていますか？",
      choices: ["つまらない", "難しいけどおもしろい", "嫌い", "簡単"],
      correctIndex: 1,
      explanation: "「書くのはおもしろい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-145",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この店は、夜の11時に閉まります。",
      question: "何時に閉まりますか？",
      choices: ["9時", "10時", "11時", "12時"],
      correctIndex: 2,
      explanation: "「11時に」閉まります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-146",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "雨が降らないうちに、買い物へ行きましょう。",
      question: "今、雨は降っていますか？",
      choices: ["降っている", "もうすぐ降る", "降っていない", "止んだ"],
      correctIndex: 2,
      explanation: "「降らないうちに」＝今はまだ降っていません。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-147",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は10年前に日本へ来ました。",
      question: "日本にどのくらいいますか？",
      choices: ["1年", "5年", "10年", "20年"],
      correctIndex: 2,
      explanation: "「10年前に来た」＝10年います。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-148",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "風が強いので、窓を閉めてください。",
      question: "どうして窓を閉めますか？",
      choices: ["寒いから", "風が強いから", "うるさいから", "暗いから"],
      correctIndex: 1,
      explanation: "「風が強い」のが理由です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-149",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このパソコンは古くて、よく壊れます。",
      question: "パソコンはどうですか？",
      choices: ["新しい", "速い", "丈夫", "よく壊れる"],
      correctIndex: 3,
      explanation: "「古くて、よく壊れる」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-150",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日は、お弁当を持ってくるのを忘れないでください。",
      question: "何を持って行きますか？",
      choices: ["辞書", "筆記用具", "お弁当", "飲み物"],
      correctIndex: 2,
      explanation: "「お弁当」を持って行きます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-151",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "図書館では静かにしてください。",
      question: "どうしなければなりませんか？",
      choices: ["歌う", "静かにする", "走る", "寝る"],
      correctIndex: 1,
      explanation: "「静かにして」ください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-152",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは、テニスだけでなく水泳も得意です。",
      question: "田中さんは何が得意ですか？",
      choices: ["テニスだけ", "水泳だけ", "テニスと水泳", "走ること"],
      correctIndex: 2,
      explanation: "両方得意です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-153",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "去年は雪が降りませんでしたが、今年はたくさん降りました。",
      question: "今年はどうですか？",
      choices: ["雪が降らなかった", "雪がたくさん降った", "雨が降った", "晴れた"],
      correctIndex: 1,
      explanation: "「今年はたくさん降り」ました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-154",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は毎朝6時に起きて、散歩をします。",
      question: "起きた後に何をしますか？",
      choices: ["朝ご飯", "仕事", "散歩", "掃除"],
      correctIndex: 2,
      explanation: "「散歩をします」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-155",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここから東京まで、新幹線で2時間半かかります。",
      question: "東京までどのくらいかかりますか？",
      choices: ["2時間", "2時間半", "3時間", "1時間"],
      correctIndex: 1,
      explanation: "「2時間半」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-156",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この部屋に入る時は、帽子を脱いでください。",
      question: "何を脱ぎますか？",
      choices: ["靴", "上着", "眼鏡", "帽子"],
      correctIndex: 3,
      explanation: "「帽子を脱いで」ください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-157",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私はお酒が嫌いなので、飲み会には行きません。",
      question: "飲み会へ行きますか？",
      choices: ["行く", "行かない", "後で行く", "時々行く"],
      correctIndex: 1,
      explanation: "「行きません」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-158",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日の試験は、9時に始まって11時に終わります。",
      question: "試験は何時間ですか？",
      choices: ["1時間", "2時間", "3時間", "4時間"],
      correctIndex: 1,
      explanation: "9時〜11時は「2時間」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-159",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この薬は、寝る前に1錠飲んでください。",
      question: "いつ飲みますか？",
      choices: ["食べる前", "食べた後", "寝る前", "起きた後"],
      correctIndex: 2,
      explanation: "「寝る前に」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-160",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日のパーティーには、50人ぐらい来ました。",
      question: "何人来ましたか？",
      choices: ["約10人", "約30人", "約50人", "約100人"],
      correctIndex: 2,
      explanation: "「50人ぐらい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-161",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "カバンの中に、財布と携帯電話が入っています。",
      question: "カバンの中に何がありますか？",
      choices: ["辞書", "鍵", "財布", "ペン"],
      correctIndex: 2,
      explanation: "「財布と携帯」が入っています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-162",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "佐藤さんは、背が低くて髪が長いです。",
      question: "佐藤さんはどんな人ですか？",
      choices: ["背が高くて髪が短い", "背が低くて髪が長い", "背が高くて髪が長い", "背が低くて髪が短い"],
      correctIndex: 1,
      explanation: "「背が低くて髪が長い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-163",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この水は、飲んでもいいですか。いいえ、だめです。",
      question: "水を飲めますか？",
      choices: ["はい", "いいえ", "後なら", "少し"],
      correctIndex: 1,
      explanation: "「いいえ、だめ」と言われています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-164",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "公園の隣に、新しい病院ができました。",
      question: "何ができましたか？",
      choices: ["スーパー", "学校", "病院", "駅"],
      correctIndex: 2,
      explanation: "「新しい病院」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-165",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "今日は暑いので、冷たい水が飲みたいです。",
      question: "何が飲みたいですか？",
      choices: ["熱い茶", "冷たい水", "甘い酒", "熱い水"],
      correctIndex: 1,
      explanation: "「冷たい水」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-166",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は、肉より魚のほうが好きです。",
      question: "何が好きですか？",
      choices: ["肉", "魚", "野菜", "卵"],
      correctIndex: 1,
      explanation: "「魚のほうが好き」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-167",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この辞書は、高かったですが、とても役に立ちます。",
      question: "辞書はどうですか？",
      choices: ["安くて便利", "高くて不便", "高くて便利", "安くて不便"],
      correctIndex: 2,
      explanation: "「高かったが、役に立つ」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-168",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "兄は25歳で、弟は20歳です。",
      question: "誰が一番年上ですか？",
      choices: ["兄", "弟", "私", "わからない"],
      correctIndex: 0,
      explanation: "兄が25歳で年上です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-169",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここにゴミを捨てないでください。",
      question: "何をしてはいけませんか？",
      choices: ["掃除", "ゴミ捨て", "食事", "喫煙"],
      correctIndex: 1,
      explanation: "「ゴミを捨てないで」ください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-170",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "映画のチケットを、2枚買いました。",
      question: "何枚買いましたか？",
      choices: ["1枚", "2枚", "3枚", "4枚"],
      correctIndex: 1,
      explanation: "「2枚」買いました。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-171",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "外は暗いので、電気をつけてください。",
      question: "どうして電気をつけますか？",
      choices: ["暑いから", "暗いから", "寒いから", "うるさいから"],
      correctIndex: 1,
      explanation: "「暗いので」が理由です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-172",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は、毎日30分日本語を話す練習をしています。",
      question: "毎日何をしていますか？",
      choices: ["読書", "料理", "話す練習", "漢字の練習"],
      correctIndex: 2,
      explanation: "「話す練習」をしています。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-173",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは、今どこにいるかわかりません。",
      question: "田中さんはどこにいますか？",
      choices: ["家", "会社", "学校", "わからない"],
      correctIndex: 3,
      explanation: "「どこにいるかわかりません」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-174",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "このバスは、15分に1本来ます。",
      question: "1時間に何本来ますか？",
      choices: ["2本", "3本", "4本", "5本"],
      correctIndex: 2,
      explanation: "60分 ÷ 15分 ＝ 4本です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-175",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日は10時に寝ましたが、今日は12時に寝ます。",
      question: "今日は何時に寝ますか？",
      choices: ["10時", "11時", "12時", "1時"],
      correctIndex: 2,
      explanation: "「今日は12時に」寝ます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-176",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "冷蔵庫の中に、卵が5個あります。",
      question: "卵はいくつありますか？",
      choices: ["3個", "4個", "5個", "6個"],
      correctIndex: 2,
      explanation: "「5個」あります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-177",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "窓の外は、雨が降っています。",
      question: "天気はどうですか？",
      choices: ["晴れ", "曇り", "雪", "雨"],
      correctIndex: 3,
      explanation: "「雨が降っている」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-178",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は、スポーツの中ではサッカーが一番好きです。",
      question: "何が一番好きですか？",
      choices: ["野球", "テニス", "サッカー", "水泳"],
      correctIndex: 2,
      explanation: "「サッカーが一番好き」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-179",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここに自転車を置かないでください。",
      question: "何を置いてはいけませんか？",
      choices: ["車", "バイク", "自転車", "荷物"],
      correctIndex: 2,
      explanation: "「自転車」を置かないでください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-180",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私の誕生日は、来月の3日です。",
      question: "誕生日はいつですか？",
      choices: ["今日", "明日", "来月の3日", "来月の10日"],
      correctIndex: 2,
      explanation: "「来月の3日」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-181",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "先生は、今会議室にいます。",
      question: "先生はどこにいますか？",
      choices: ["教室", "事務所", "食堂", "会議室"],
      correctIndex: 3,
      explanation: "「会議室に」います。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-182",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この料理は、辛くないので、子どもでも食べられます。",
      question: "子どもは食べられますか？",
      choices: ["はい", "いいえ", "わからない", "大人だけ"],
      correctIndex: 0,
      explanation: "「食べられます」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-183",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "昨日は忙しかったですが、今日は暇です。",
      question: "今日の予定はどうですか？",
      choices: ["忙しい", "暇", "仕事がある", "わからない"],
      correctIndex: 1,
      explanation: "「今日は暇」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-184",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "明日のパーティーには、飲み物を持ってきてください。",
      question: "何を持って行きますか？",
      choices: ["料理", "お菓子", "飲み物", "花"],
      correctIndex: 2,
      explanation: "「飲み物を持ってきて」ください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-185",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は、毎日1時間運動をしています。",
      question: "毎日何をしていますか？",
      choices: ["勉強", "料理", "掃除", "運動"],
      correctIndex: 3,
      explanation: "「運動をしています」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-186",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この靴は、私には少し大きいです。",
      question: "靴はどうですか？",
      choices: ["小さい", "大きい", "ちょうどいい", "短い"],
      correctIndex: 1,
      explanation: "「少し大きい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-187",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "駅から家まで、歩いて15分かかります。",
      question: "家までどのくらいかかりますか？",
      choices: ["5分", "10分", "15分", "20分"],
      correctIndex: 2,
      explanation: "「15分」かかります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-188",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は、お菓子より果物のほうが好きです。",
      question: "何が好きですか？",
      choices: ["お菓子", "果物", "ケーキ", "アイス"],
      correctIndex: 1,
      explanation: "「果物のほうが好き」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-189",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この部屋は、エアコンをつけているので涼しいです。",
      question: "部屋はどうですか？",
      choices: ["暑い", "寒い", "涼しい", "暗い"],
      correctIndex: 2,
      explanation: "「涼しい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-190",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "田中さんは、昨日病院へ行きました。",
      question: "田中さんは昨日、どこへ行きましたか？",
      choices: ["学校", "会社", "病院", "公園"],
      correctIndex: 2,
      explanation: "「病院へ行きました」。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-191",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私の趣味は、音楽を聴くことです。",
      question: "趣味は何ですか？",
      choices: ["スポーツ", "読書", "料理", "音楽を聴く"],
      correctIndex: 3,
      explanation: "「音楽を聴くこと」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-192",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この本は、とても面白くて読みやすいです。",
      question: "本はどうですか？",
      choices: ["面白くない", "面白くて読みやすい", "難しい", "長い"],
      correctIndex: 1,
      explanation: "「面白くて読みやすい」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-193",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は、毎日6時半に起きます。",
      question: "何時に起きますか？",
      choices: ["6時", "6時半", "7時", "7時半"],
      correctIndex: 1,
      explanation: "「6時半」に起きます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-194",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "冷蔵庫の中に、水が3本あります。",
      question: "水は何本ありますか？",
      choices: ["1本", "2本", "3本", "4本"],
      correctIndex: 2,
      explanation: "「3本」あります。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-195",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "窓の外は、風が強くて危ないです。",
      question: "外はどうですか？",
      choices: ["静か", "天気がいい", "風が強くて危ない", "暑い"],
      correctIndex: 2,
      explanation: "「風が強くて危ない」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-196",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私は、肉が好きですが、野菜もよく食べます。",
      question: "何を食べますか？",
      choices: ["肉だけ", "野菜だけ", "肉と野菜", "何も食べない"],
      correctIndex: 2,
      explanation: "両方食べます。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-197",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "ここに名前を書いて、ハンコを押してください。",
      question: "何を書きますか？",
      choices: ["住所", "電話番号", "名前", "年齢"],
      correctIndex: 2,
      explanation: "「名前を書いて」ください。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-198",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "私の誕生日は、12月25日です。",
      question: "誕生日はいつですか？",
      choices: ["1月1日", "5月5日", "12月25日", "12月31日"],
      correctIndex: 2,
      explanation: "「12月25日」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-199",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "先生は、今図書室にいます。",
      question: "先生はどこにいますか？",
      choices: ["教室", "事務所", "食堂", "図書室"],
      correctIndex: 3,
      explanation: "「図書室に」います。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "mb-n4-200",
      kind: "memory-burst",
      sectionId: "reading",
      displayText: "この料理は、とても美味しくて安いです。",
      question: "料理はどうですか？",
      choices: ["高くて美味しい", "安くて不味い", "安くて美味しい", "高くて不味い"],
      correctIndex: 2,
      explanation: "「美味しくて安い」です。",
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },

  ],
}

export function getMemoryBurstPool(quizType: QuizType) {
  const list = memoryBurstPools[quizType] ?? []
  return list.filter((q) => q.enabled)
}
