// app/(auth)/game/pools/tileDropPools.ts
import type { QuizType } from "@/app/data/types"
import type { GameQuestion } from "../types"

// ✅ 落ちゲー専用プール
// - 型B（穴埋め/助詞）と型C（読み分解）を中心
// - 型A（並べ替え）は入れない

export const tileDropPools: Partial<Record<QuizType, GameQuestion[]>> = {
  "japanese-n4": [
    // ===== 型B：穴埋め（助詞/活用） =====
    {
      id: "td-n4-b-001",
      kind: "tile-drop",
      type: "fill",
      sectionId: "bunpo",
      prompt: "私は学校（　）日本語（　）勉強します。",
      answer: ["で", "を"],
      choices: ["で", "を", "に", "が", "へ", "と"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-b-002",
      kind: "tile-drop",
      type: "fill",
      sectionId: "bunpo",
      prompt: "ここ（　）入ってはいけません。",
      answer: ["に"],
      choices: ["に", "で", "を", "へ", "が", "から"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-b-003",
      kind: "tile-drop",
      type: "fill",
      sectionId: "bunpo",
      prompt: "雨（　）降ったので、出かけませんでした。",
      answer: ["が"],
      choices: ["が", "を", "に", "で", "から", "まで"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-b-004",
      kind: "tile-drop",
      type: "fill",
      sectionId: "bunpo",
      prompt: "すみません、駅（　）行きたいです。",
      answer: ["に"],
      choices: ["に", "を", "で", "へ", "と", "から"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },

    // ===== 型C：読み分解（漢字→かな） =====
    {
      id: "td-n4-c-001",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "現場",
      answer: ["げ", "ん", "ば"],
      choices: ["げ", "ん", "ば", "け", "ま", "は"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-002",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "道具",
      answer: ["ど", "う", "ぐ"],
      choices: ["ど", "う", "ぐ", "と", "く", "き"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-003",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "不便",
      answer: ["ふ", "べ", "ん"],
      choices: ["ふ", "べ", "ん", "ぷ", "へ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-004",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "産業",
      answer: ["さ", "ん", "ぎ", "ょ", "う"],
      choices: ["さ", "ん", "ぎ", "ょ", "う", "ぜ", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-005",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "案内",
      answer: ["あ", "ん", "な", "い"],
      choices: ["あ", "ん", "な", "い", "は", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-006",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "試合",
      answer: ["し", "あ", "い"],
      choices: ["し", "あ", "い", "じ", "や", "え"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-007",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "目的",
      answer: ["も", "く", "て", "き"],
      choices: ["も", "く", "て", "き", "め", "で"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-008",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "世話",
      answer: ["せ", "わ"],
      choices: ["せ", "わ", "ぜ", "は", "る", "ね"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-009",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地理",
      answer: ["ち", "り"],
      choices: ["ち", "り", "じ", "し", "に", "ね"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-010",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "以外",
      answer: ["い", "が", "い"],
      choices: ["い", "が", "い", "に", "か", "き"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-011",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "説明",
      answer: ["せ", "つ", "め", "い"],
      choices: ["せ", "つ", "め", "い", "ぜ", "ち"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-012",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "卒業",
      answer: ["そ", "つ", "ぎ", "ょ", "う"],
      choices: ["そ", "つ", "ぎ", "ょ", "う", "し", "ょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-013",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "台所",
      answer: ["だ", "い", "ど", "こ", "ろ"],
      choices: ["だ", "い", "ど", "こ", "ろ", "た", "と"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-014",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "予習",
      answer: ["よ", "し", "ゅ", "う"],
      choices: ["よ", "し", "ゅ", "う", "っ", "ょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-015",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "急行",
      answer: ["き", "ゅ", "う", "こ", "う"],
      choices: ["き", "ゅ", "う", "こ", "う", "きょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-016",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "計画",
      answer: ["け", "い", "か", "く"],
      choices: ["け", "い", "か", "く", "がい", "き"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-017",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "意見",
      answer: ["い", "け", "ん"],
      choices: ["い", "け", "ん", "あ", "げ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-018",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "返事",
      answer: ["へ", "ん", "じ"],
      choices: ["へ", "ん", "じ", "べ", "ば", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-019",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地震",
      answer: ["じ", "し", "ん"],
      choices: ["じ", "し", "ん", "ち", "ぜ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-020",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "住所",
      answer: ["じ", "ゅ", "う", "し", "ょ"],
      choices: ["じ", "ゅ", "う", "し", "ょ", "じょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-021",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "法律",
      answer: ["ほ", "う", "り", "つ"],
      choices: ["ほ", "う", "り", "つ", "ぼ", "ふ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-022",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "複雑",
      answer: ["ふ", "く", "ざ", "つ"],
      choices: ["ふ", "く", "ざ", "つ", "ぷ", "さ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-023",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "技術",
      answer: ["ぎ", "じ", "ゅ", "つ"],
      choices: ["ぎ", "じ", "ゅ", "つ", "き", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-024",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "広告",
      answer: ["こ", "う", "こ", "く"],
      choices: ["こ", "う", "こ", "く", "ご", "う"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-025",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "貿易",
      answer: ["ぼ", "う", "え", "き"],
      choices: ["ぼ", "う", "え", "き", "ほ", "は"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-026",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "経験",
      answer: ["け", "い", "け", "ん"],
      choices: ["け", "い", "け", "ん", "げ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-027",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "景色",
      answer: ["け", "し", "き"],
      choices: ["け", "し", "き", "げ", "じ", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-028",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "故障",
      answer: ["こ", "し", "ょ", "う"],
      choices: ["こ", "し", "ょ", "う", "ご", "そ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-029",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "招待",
      answer: ["し", "ょ", "う", "た", "い"],
      choices: ["し", "ょ", "う", "た", "い", "じ", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-030",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "政治",
      answer: ["せ", "い", "じ"],
      choices: ["せ", "い", "じ", "ぜ", "し", "ち"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-031",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "準備",
      answer: ["じ", "ゅ", "ん", "び"],
      choices: ["じ", "ゅ", "ん", "び", "ち", "ひ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-032",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "連絡",
      answer: ["れ", "ん", "ら", "く"],
      choices: ["れ", "ん", "ら", "く", "ね", "ろ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-033",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "理由",
      answer: ["り", "ゆ", "う"],
      choices: ["り", "ゆ", "う", "い", "よ", "る"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-034",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "相談",
      answer: ["そ", "う", "だ", "ん"],
      choices: ["そ", "う", "だ", "ん", "ぞ", "た"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-035",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "賛成",
      answer: ["さ", "ん", "せ", "い"],
      choices: ["さ", "ん", "せ", "い", "ざ", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-036",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "反対",
      answer: ["は", "ん", "た", "い"],
      choices: ["は", "ん", "た", "い", "ば", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-037",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "市役所",
      answer: ["し", "や", "く", "し", "ょ"],
      choices: ["し", "や", "く", "し", "ょ", "じ", "ゃ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-038",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "駐車場",
      answer: ["ち", "ゅ", "う", "し", "ゃ", "じ", "ょ", "う"],
      choices: ["ち", "ゅ", "う", "し", "ゃ", "じ", "ょ", "う"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-039",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "出席",
      answer: ["し", "ゅ", "っ", "せ", "き"],
      choices: ["し", "ゅ", "っ", "せ", "き", "じ", "す"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-040",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "欠席",
      answer: ["け", "っ", "せ", "き"],
      choices: ["け", "っ", "せ", "き", "げ", "そ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-041",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "特急",
      answer: ["と", "っ", "き", "ゅ", "う"],
      choices: ["と", "っ", "き", "ゅ", "う", "ど", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-042",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "記念",
      answer: ["き", "ね", "ん"],
      choices: ["き", "ね", "ん", "ぎ", "れ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-043",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "変化",
      answer: ["へ", "ん", "か"],
      choices: ["へ", "ん", "か", "べ", "が", "は"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-044",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "成功",
      answer: ["せ", "い", "こ", "う"],
      choices: ["せ", "い", "こ", "う", "ぜ", "ご"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-045",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "失敗",
      answer: ["し", "っ", "ぱ", "い"],
      choices: ["し", "っ", "ぱ", "い", "じ", "ば"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-046",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "結局",
      answer: ["け", "っ", "き", "ょ", "く"],
      choices: ["け", "っ", "き", "ょ", "く", "げ", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-047",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "興味",
      answer: ["き", "ょ", "う", "み"],
      choices: ["き", "ょ", "う", "み", "ぎ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-048",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "意味",
      answer: ["い", "み"],
      choices: ["い", "み", "に", "め", "り"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-049",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "質問",
      answer: ["し", "つ", "も", "ん"],
      choices: ["し", "つ", "も", "ん", "じ", "ち"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-050",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "説明",
      answer: ["せ", "つ", "め", "い"],
      choices: ["せ", "つ", "め", "い", "ぜ", "ね"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-051",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "注意",
      answer: ["ち", "ゅ", "う", "い"],
      choices: ["ち", "ゅ", "う", "い", "じ", "ゆ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-052",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "習慣",
      answer: ["し", "ゅ", "う", "か", "ん"],
      choices: ["し", "ゅ", "う", "か", "ん", "じ", "き"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-053",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "将来",
      answer: ["し", "ょ", "う", "ら", "い"],
      choices: ["し", "ょ", "う", "ら", "い", "じ", "な"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-054",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "相手",
      answer: ["あ", "い", "て"],
      choices: ["あ", "い", "て", "わ", "で", "る"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-055",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "相談",
      answer: ["そ", "う", "だ", "ん"],
      choices: ["そ", "う", "だ", "ん", "ぞ", "ん"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-056",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "安心",
      answer: ["あ", "ん", "し", "ん"],
      choices: ["あ", "ん", "し", "ん", "は", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-057",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "心配",
      answer: ["し", "ん", "ぱ", "い"],
      choices: ["し", "ん", "ぱ", "い", "じ", "ば"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-058",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "安全",
      answer: ["あ", "ん", "ぜ", "ん"],
      choices: ["あ", "ん", "ぜ", "ん", "は", "せ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-059",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "危険",
      answer: ["き", "け", "ん"],
      choices: ["き", "け", "ん", "ぎ", "げ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-060",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "目的",
      answer: ["も", "く", "て", "き"],
      choices: ["も", "く", "て", "き", "め", "で"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-061",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "経験",
      answer: ["け", "い", "け", "ん"],
      choices: ["け", "い", "け", "ん", "げ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-062",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "景色",
      answer: ["け", "し", "き"],
      choices: ["け", "し", "き", "げ", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-063",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "故障",
      answer: ["こ", "し", "ょ", "う"],
      choices: ["こ", "し", "ょ", "う", "ご", "そ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-064",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "招待",
      answer: ["し", "ょ", "う", "た", "い"],
      choices: ["し", "ょ", "う", "た", "い", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-065",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "政治",
      answer: ["せ", "い", "じ"],
      choices: ["せ", "い", "じ", "ぜ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-066",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "準備",
      answer: ["じ", "ゅ", "ん", "び"],
      choices: ["じ", "ゅ", "ん", "び", "ち", "ひ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-067",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "連絡",
      answer: ["れ", "ん", "ら", "く"],
      choices: ["れ", "ん", "ら", "く", "ね", "ろ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-068",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "理由",
      answer: ["り", "ゆ", "う"],
      choices: ["り", "ゆ", "う", "い", "よ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-069",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "相談",
      answer: ["そ", "う", "だ", "ん"],
      choices: ["そ", "う", "だ", "ん", "ぞ", "た"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-070",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "賛成",
      answer: ["さ", "ん", "せ", "い"],
      choices: ["さ", "ん", "せ", "い", "ざ", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-071",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "反対",
      answer: ["は", "ん", "た", "い"],
      choices: ["は", "ん", "た", "い", "ば", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-072",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "産業",
      answer: ["さ", "ん", "ぎ", "ょ", "う"],
      choices: ["さ", "ん", "ぎ", "ょ", "う", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-073",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "技術",
      answer: ["ぎ", "じ", "ゅ", "つ"],
      choices: ["ぎ", "じ", "ゅ", "つ", "き", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-074",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "複雑",
      answer: ["ふ", "く", "ざ", "つ"],
      choices: ["ふ", "く", "ざ", "つ", "ぷ", "さ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-075",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "貿易",
      answer: ["ぼ", "う", "え", "き"],
      choices: ["ぼ", "う", "え", "き", "ほ", "は"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-076",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "法律",
      answer: ["ほ", "う", "り", "つ"],
      choices: ["ほ", "う", "り", "つ", "ぼ", "ふ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-077",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "広告",
      answer: ["こ", "う", "こ", "く"],
      choices: ["こ", "う", "こ", "く", "ご", "う"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-078",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "放送",
      answer: ["ほ", "う", "そ", "う"],
      choices: ["ほ", "う", "そ", "う", "ぼ", "ぞ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-079",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "記事",
      answer: ["き", "じ"],
      choices: ["き", "じ", "ぎ", "し", "ち"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-080",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "適当",
      answer: ["て", "き", "と", "う"],
      choices: ["て", "き", "と", "う", "で", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-081",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "特急",
      answer: ["と", "っ", "き", "ゅ", "う"],
      choices: ["と", "っ", "き", "ゅ", "う", "ど"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-082",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "直接",
      answer: ["ち", "ょ", "く", "せ", "つ"],
      choices: ["ち", "ょ", "く", "せ", "つ", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-083",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "丁寧",
      answer: ["て", "い", "ね", "い"],
      choices: ["て", "い", "ね", "い", "で", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-084",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "残念",
      answer: ["ざ", "ん", "ね", "ん"],
      choices: ["ざ", "ん", "ね", "ん", "さ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-085",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "記念",
      answer: ["き", "ね", "ん"],
      choices: ["き", "ね", "ん", "ぎ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-086",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "郵便",
      answer: ["ゆ", "う", "び", "ん"],
      choices: ["ゆ", "う", "び", "ん", "よ", "ひ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-087",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "宅配",
      answer: ["た", "く", "は", "い"],
      choices: ["た", "く", "は", "い", "だ", "ば"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-088",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "配達",
      answer: ["は", "い", "た", "つ"],
      choices: ["は", "い", "た", "つ", "ば", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-089",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "期待",
      answer: ["き", "た", "い"],
      choices: ["き", "た", "い", "ぎ", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-090",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "変化",
      answer: ["へ", "ん", "か"],
      choices: ["へ", "ん", "か", "べ", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-091",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "発表",
      answer: ["は", "っ", "ぴ", "ょ", "う"],
      choices: ["は", "っ", "ぴ", "ょ", "う", "ば"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-092",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "表面",
      answer: ["ひ", "ょ", "う", "め", "ん"],
      choices: ["ひ", "ょ", "う", "め", "ん", "び"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-093",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "調査",
      answer: ["ち", "ょ", "う", "さ"],
      choices: ["ち", "ょ", "う", "さ", "じ", "ぞ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-094",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "検査",
      answer: ["け", "ん", "さ"],
      choices: ["け", "ん", "さ", "げ", "ざ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-095",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "世紀",
      answer: ["せ", "い", "き"],
      choices: ["せ", "い", "き", "ぜ", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-096",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "未来",
      answer: ["み", "ら", "い"],
      choices: ["み", "ら", "い", "め", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-097",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "過去",
      answer: ["か", "こ"],
      choices: ["か", "こ", "が", "ご"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-098",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "歴史",
      answer: ["れ", "き", "し"],
      choices: ["れ", "き", "し", "ね", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-099",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "世界",
      answer: ["せ", "か", "い"],
      choices: ["せ", "か", "い", "ぜ", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-100",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "国際",
      answer: ["こ", "く", "さ", "い"],
      choices: ["こ", "く", "さ", "い", "ご", "ざ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-101",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "案内",
      answer: ["あ", "ん", "な", "い"],
      choices: ["あ", "ん", "な", "い", "は", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-102",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "準備",
      answer: ["じ", "ゅ", "ん", "び"],
      choices: ["じ", "ゅ", "ん", "び", "ち", "ひ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-103",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "世話",
      answer: ["せ", "わ"],
      choices: ["せ", "わ", "ぜ", "は", "る"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-104",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "複雑",
      answer: ["ふ", "く", "ざ", "つ"],
      choices: ["ふ", "く", "ざ", "つ", "ぷ", "さ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-105",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "法律",
      answer: ["ほ", "う", "り", "つ"],
      choices: ["ほ", "う", "り", "つ", "ぼ", "ふ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-106",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "相談",
      answer: ["そ", "う", "だ", "ん"],
      choices: ["そ", "う", "だ", "ん", "ぞ", "た"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-107",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "賛成",
      answer: ["さ", "ん", "せ", "い"],
      choices: ["さ", "ん", "せ", "い", "ざ", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-108",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "反対",
      answer: ["は", "ん", "た", "い"],
      choices: ["は", "ん", "た", "い", "ば", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-109",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "産業",
      answer: ["さ", "ん", "ぎ", "ょ", "う"],
      choices: ["さ", "ん", "ぎ", "ょ", "う", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-110",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "輸出",
      answer: ["ゆ", "し", "ゅ", "つ"],
      choices: ["ゆ", "し", "ゅ", "つ", "よ", "す"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-111",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "輸入",
      answer: ["ゆ", "に", "ゅ", "う"],
      choices: ["ゆ", "に", "ゅ", "う", "よ", "に"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-112",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "成功",
      answer: ["せ", "い", "こ", "う"],
      choices: ["せ", "い", "こ", "う", "ぜ", "ご"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-113",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "失敗",
      answer: ["し", "っ", "ぱ", "い"],
      choices: ["し", "っ", "ぱ", "い", "じ", "ば"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-114",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "経済",
      answer: ["け", "い", "ざ", "い"],
      choices: ["け", "い", "ざ", "い", "げ", "さ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-115",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "故障",
      answer: ["こ", "し", "ょ", "う"],
      choices: ["こ", "し", "ょ", "う", "ご", "そ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-116",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "修理",
      answer: ["し", "ゅ", "う", "り"],
      choices: ["し", "ゅ", "う", "り", "じ", "る"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-117",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "連絡",
      answer: ["れ", "ん", "ら", "く"],
      choices: ["れ", "ん", "ら", "く", "ね", "ろ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-118",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "理由",
      answer: ["り", "ゆ", "う"],
      choices: ["り", "ゆ", "う", "い", "よ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-120",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "政治",
      answer: ["せ", "い", "じ"],
      choices: ["せ", "い", "じ", "ぜ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-121",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "道具",
      answer: ["ど", "う", "ぐ"],
      choices: ["ど", "う", "ぐ", "と", "く"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-122",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "景色",
      answer: ["け", "し", "き"],
      choices: ["け", "し", "き", "げ", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-123",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "記念",
      answer: ["き", "ね", "ん"],
      choices: ["き", "ね", "ん", "ぎ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-124",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "記事",
      answer: ["き", "じ"],
      choices: ["き", "じ", "ぎ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-125",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "放送",
      answer: ["ほ", "う", "そ", "う"],
      choices: ["ほ", "う", "そ", "う", "ぼ", "ぞ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-126",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "丁寧",
      answer: ["て", "い", "ね", "い"],
      choices: ["て", "い", "ね", "い", "で", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-127",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "直接",
      answer: ["ち", "ょ", "く", "せ", "つ"],
      choices: ["ち", "ょ", "く", "せ", "つ", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-128",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "適当",
      answer: ["て", "き", "と", "う"],
      choices: ["て", "き", "と", "う", "で", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-129",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "非常",
      answer: ["ひ", "じ", "ょ", "う"],
      choices: ["ひ", "じ", "ょ", "う", "び", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-130",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "紹介",
      answer: ["し", "ょ", "う", "か", "い"],
      choices: ["し", "ょ", "う", "か", "い", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-131",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "練習",
      answer: ["れ", "ん", "し", "ゅ", "う"],
      choices: ["れ", "ん", "し", "ゅ", "う", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-132",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "習慣",
      answer: ["し", "ゅ", "う", "か", "ん"],
      choices: ["し", "ゅ", "う", "か", "ん", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-133",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "科学",
      answer: ["か", "が", "く"],
      choices: ["か", "が", "く", "き", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-134",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "文学",
      answer: ["ぶ", "ん", "が", "く"],
      choices: ["ぶ", "ん", "が", "く", "ふ", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-135",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地理",
      answer: ["ち", "り"],
      choices: ["ち", "り", "じ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-136",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "歴史",
      answer: ["れ", "き", "し"],
      choices: ["れ", "き", "し", "ね", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-137",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "医学",
      answer: ["い", "が", "く"],
      choices: ["い", "が", "く", "に", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-138",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "授業",
      answer: ["じ", "ゅ", "ぎ", "ょ", "う"],
      choices: ["じ", "ゅ", "ぎ", "ょ", "う", "ち"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-139",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "卒業",
      answer: ["そ", "つ", "ぎ", "ょ", "う"],
      choices: ["そ", "つ", "ぎ", "ょ", "う", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-140",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "予習",
      answer: ["よ", "し", "ゅ", "う"],
      choices: ["よ", "し", "ゅ", "う", "っ", "ょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-141",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "復習",
      answer: ["ふ", "く", "し", "ゅ", "う"],
      choices: ["ふ", "く", "し", "ゅ", "う", "す"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-142",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "研究",
      answer: ["け", "ん", "き", "ゅ", "う"],
      choices: ["け", "ん", "き", "ゅ", "う", "げ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-143",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "会場",
      answer: ["か", "い", "じ", "ょ", "う"],
      choices: ["か", "い", "じ", "ょ", "う", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-144",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "出席",
      answer: ["し", "ゅ", "っ", "せ", "き"],
      choices: ["し", "ゅ", "っ", "せ", "き", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-145",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "欠席",
      answer: ["け", "っ", "せ", "き"],
      choices: ["け", "っ", "せ", "き", "げ", "そ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-146",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "注意",
      answer: ["ち", "ゅ", "う", "い"],
      choices: ["ち", "ゅ", "う", "い", "じ", "ゆ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-147",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "質問",
      answer: ["し", "つ", "も", "ん"],
      choices: ["し", "つ", "も", "ん", "じ", "ち"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-148",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "回答",
      answer: ["か", "い", "と", "う"],
      choices: ["か", "い", "と", "う", "が", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-149",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "目的",
      answer: ["も", "く", "て", "き"],
      choices: ["も", "く", "て", "き", "め", "で"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-150",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "方法",
      answer: ["ほ", "う", "ほ", "う"],
      choices: ["ほ", "う", "ほ", "う", "ぼ", "う"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-151",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "技術",
      answer: ["ぎ", "じ", "ゅ", "つ"],
      choices: ["ぎ", "じ", "ゅ", "つ", "き", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-152",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "住所",
      answer: ["じ", "ゅ", "う", "し", "ょ"],
      choices: ["じ", "ゅ", "う", "し", "ょ", "じょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-153",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "近所",
      answer: ["き", "ん", "じ", "ょ"],
      choices: ["き", "ん", "じ", "ょ", "き", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-154",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "台所",
      answer: ["だ", "い", "ど", "こ", "ろ"],
      choices: ["だ", "い", "ど", "こ", "ろ", "た"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-155",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "場所",
      answer: ["ば", "し", "ょ"],
      choices: ["ば", "し", "ょ", "は", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-156",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "工場",
      answer: ["こ", "う", "じ", "ょ", "う"],
      choices: ["こ", "う", "じ", "ょ", "う", "ご"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-157",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "売り場",
      answer: ["う", "り", "ば"],
      choices: ["う", "り", "ば", "は", "ぱ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-158",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "入場",
      answer: ["に", "ゅ", "う", "じ", "ょ", "う"],
      choices: ["に", "ゅ", "う", "じ", "ょ", "う"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-159",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "役所",
      answer: ["や", "く", "し", "ょ"],
      choices: ["や", "く", "し", "ょ", "あ", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-160",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "近所",
      answer: ["き", "ん", "じ", "ょ"],
      choices: ["き", "ん", "じ", "ょ", "ぎ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-161",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "研究所",
      answer: ["け", "ん", "き", "ゅ", "う", "じ", "ょ"],
      choices: ["け", "ん", "き", "ゅ", "う", "じ", "ょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-162",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "市役所",
      answer: ["し", "や", "く", "し", "ょ"],
      choices: ["し", "や", "く", "し", "ょ", "じ", "ゃ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-163",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "都合",
      answer: ["つ", "ご", "う"],
      choices: ["つ", "ご", "う", "ず", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-164",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "集合",
      answer: ["し", "ゅ", "う", "ご", "う"],
      choices: ["し", "ゅ", "う", "ご", "う", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-165",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "会合",
      answer: ["か", "い", "ご", "う"],
      choices: ["か", "い", "ご", "う", "が", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-166",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "場合",
      answer: ["ば", "あ", "い"],
      choices: ["ば", "あ", "い", "は", "え"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-167",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "割合",
      answer: ["わ", "り", "あ", "い"],
      choices: ["わ", "り", "あ", "い", "え", "る"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-168",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "試合",
      answer: ["し", "あ", "い"],
      choices: ["し", "あ", "い", "じ", "や"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-169",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "間に合う",
      answer: ["ま", "に", "あ", "う"],
      choices: ["ま", "に", "あ", "う", "め", "い"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-170",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "合格",
      answer: ["ご", "う", "か", "く"],
      choices: ["ご", "う", "か", "く", "こ", "き"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-171",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "目的",
      answer: ["も", "く", "て", "き"],
      choices: ["も", "く", "て", "き", "め", "で"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-172",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "目標",
      answer: ["も", "く", "ひ", "ょ", "う"],
      choices: ["も", "く", "ひ", "ょ", "う", "び"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-173",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "目安",
      answer: ["め", "や", "す"],
      choices: ["め", "あ", "す", "に", "は"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-174",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "注目",
      answer: ["ち", "ゅ", "う", "も", "く"],
      choices: ["ち", "ゅ", "う", "も", "く", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-175",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "面白い",
      answer: ["お", "も", "し", "ろ", "い"],
      choices: ["お", "も", "し", "ろ", "い", "に"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-176",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "真面目",
      answer: ["ま", "じ", "め"],
      choices: ["ま", "じ", "め", "ば", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-177",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "方面",
      answer: ["ほ", "う", "め", "ん"],
      choices: ["ほ", "う", "め", "ん", "ぼ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-178",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "表面",
      answer: ["ひ", "ょ", "う", "め", "ん"],
      choices: ["ひ", "ょ", "う", "め", "ん", "び"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-179",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "会見",
      answer: ["か", "い", "け", "ん"],
      choices: ["か", "い", "け", "ん", "が", "げ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-180",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "見学",
      answer: ["け", "ん", "が", "く"],
      choices: ["け", "ん", "が", "く", "げ", "き"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-181",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "見本",
      answer: ["み", "ほ", "ん"],
      choices: ["み", "ほ", "ん", "め", "ぼ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-182",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "意見",
      answer: ["い", "け", "ん"],
      choices: ["い", "け", "ん", "あ", "げ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-183",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "拝見",
      answer: ["は", "い", "け", "ん"],
      choices: ["は", "い", "け", "ん", "ば", "げ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-184",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "建物",
      answer: ["た", "て", "も", "の"],
      choices: ["た", "て", "も", "の", "だ", "ぬ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-185",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "食べ物",
      answer: ["た", "べ", "も", "の"],
      choices: ["た", "べ", "も", "の", "だ", "へ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-186",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "飲み物",
      answer: ["の", "み", "も", "の"],
      choices: ["の", "み", "も", "の", "ぬ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-187",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "買い物",
      answer: ["か", "い", "も", "の"],
      choices: ["か", "い", "も", "の", "が", "ぬ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-188",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "贈り物",
      answer: ["お", "く", "り", "も", "の"],
      choices: ["お", "く", "り", "も", "の", "ご"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-189",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "荷物",
      answer: ["に", "も", "つ"],
      choices: ["に", "も", "つ", "ぬ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-190",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "動物",
      answer: ["ど", "う", "ぶ", "つ"],
      choices: ["ど", "う", "ぶ", "つ", "と", "ふ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-191",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "植物",
      answer: ["し", "ょ", "く", "ぶ", "つ"],
      choices: ["し", "ょ", "く", "ぶ", "つ", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-192",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "物事",
      answer: ["も", "の", "ご", "と"],
      choices: ["も", "の", "ご", "と", "ぬ", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-193",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "見物",
      answer: ["け", "ん", "ぶ", "つ"],
      choices: ["け", "ん", "ぶ", "つ", "げ", "ふ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-194",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "動作",
      answer: ["ど", "う", "さ"],
      choices: ["ど", "う", "さ", "と", "ざ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-195",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "作業",
      answer: ["さ", "ぎ", "ょ", "う"],
      choices: ["さ", "ぎ", "ょ", "う", "ざ", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-196",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "手作り",
      answer: ["て", "づ", "く", "り"],
      choices: ["て", "づ", "く", "り", "で", "つ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-197",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "作文",
      answer: ["さ", "く", "ぶ", "ん"],
      choices: ["さ", "く", "ぶ", "ん", "ざ", "ぷ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-198",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "制作",
      answer: ["せ", "い", "さ", "く"],
      choices: ["せ", "い", "さ", "く", "ぜ", "ざ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-199",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "運動",
      answer: ["う", "ん", "ど", "う"],
      choices: ["う", "ん", "ど", "う", "と", "う"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-200",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "自動車",
      answer: ["じ", "ど", "う", "し", "ゃ"],
      choices: ["じ", "ど", "う", "し", "ゃ", "ち"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-201",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "計画",
      answer: ["け", "い", "か", "く"],
      choices: ["け", "い", "か", "く", "げ", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-202",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "画家",
      answer: ["が", "か"],
      choices: ["が", "か", "か", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-203",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "映画",
      answer: ["え", "い", "が"],
      choices: ["え", "い", "が", "き", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-204",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "漫画",
      answer: ["ま", "ん", "が"],
      choices: ["ま", "ん", "が", "は", "か"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-205",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地震",
      answer: ["じ", "し", "ん"],
      choices: ["じ", "し", "ん", "ち", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-206",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地下鉄",
      answer: ["ち", "か", "て", "つ"],
      choices: ["ち", "か", "て", "つ", "じ", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-207",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地図",
      answer: ["ち", "ず"],
      choices: ["ち", "ず", "じ", "す"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-208",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地方",
      answer: ["ち", "ほ", "う"],
      choices: ["ち", "ほ", "う", "じ", "ぼ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-209",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "意味",
      answer: ["い", "み"],
      choices: ["い", "み", "に", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-210",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "趣味",
      answer: ["し", "ゅ", "み"],
      choices: ["し", "ゅ", "み", "じ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-211",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "興味",
      answer: ["き", "ょ", "う", "み"],
      choices: ["き", "ょ", "う", "み", "ぎ", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-212",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "味噌",
      answer: ["み", "そ"],
      choices: ["み", "そ", "め", "ぞ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-213",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "去年",
      answer: ["き", "ょ", "ね", "ん"],
      choices: ["き", "ょ", "ね", "ん", "ぎ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-214",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "過去",
      answer: ["か", "こ"],
      choices: ["か", "こ", "が", "ご"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-215",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "辞退",
      answer: ["じ", "た", "い"],
      choices: ["じ", "た", "い", "し", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-216",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "辞典",
      answer: ["じ", "て", "ん"],
      choices: ["じ", "て", "ん", "し", "で"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-217",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "辞書",
      answer: ["じ", "し", "ょ"],
      choices: ["じ", "し", "ょ", "し", "じょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-218",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "記事",
      answer: ["き", "じ"],
      choices: ["き", "じ", "ぎ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-219",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "食事",
      answer: ["し", "ょ", "く", "じ"],
      choices: ["し", "ょ", "く", "じ", "じょ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-220",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "火事",
      answer: ["か", "じ"],
      choices: ["か", "じ", "が", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-221",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "大事",
      answer: ["だ", "い", "じ"],
      choices: ["だ", "い", "じ", "た", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-222",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "返事",
      answer: ["へ", "ん", "じ"],
      choices: ["へ", "ん", "じ", "べ", "ば"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-223",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "習い事",
      answer: ["な", "ら", "い", "ご", "と"],
      choices: ["な", "ら", "い", "ご", "と", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-224",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "都会",
      answer: ["と", "か", "い"],
      choices: ["と", "か", "い", "ど", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-225",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "都合",
      answer: ["つ", "ご", "う"],
      choices: ["つ", "ご", "う", "ず", "こ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-226",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "京都",
      answer: ["き", "ょ", "う", "と"],
      choices: ["き", "ょ", "う", "と", "ぎ", "ど"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-227",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "発音",
      answer: ["は", "つ", "お", "ん"],
      choices: ["は", "つ", "お", "ん", "ば", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-228",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "本音",
      answer: ["ほ", "ん", "ね"],
      choices: ["ほ", "ん", "ね", "ぼ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-229",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "音楽",
      answer: ["お", "ん", "が", "く"],
      choices: ["お", "ん", "が", "く", "あん", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-230",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "楽",
      answer: ["ら", "く"],
      choices: ["ら", "く", "な", "ろ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-231",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "楽器",
      answer: ["が", "っ", "き"],
      choices: ["が", "っ", "き", "か", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-232",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "特別",
      answer: ["と", "く", "べ", "つ"],
      choices: ["と", "く", "べ", "つ", "ど", "へ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-233",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "別れる",
      answer: ["わ", "か", "れ", "る"],
      choices: ["わ", "か", "れ", "る", "は", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-234",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "送別会",
      answer: ["そ", "う", "べ", "つ", "か", "い"],
      choices: ["そ", "う", "べ", "つ", "か", "い", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-235",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "世界",
      answer: ["せ", "か", "い"],
      choices: ["せ", "か", "い", "ぜ", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-236",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "限界",
      answer: ["げ", "ん", "か", "い"],
      choices: ["げ", "ん", "か", "い", "け", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-237",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "医学",
      answer: ["い", "が", "く"],
      choices: ["い", "が", "く", "に", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-238",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "歯医者",
      answer: ["は", "い", "し", "ゃ"],
      choices: ["は", "い", "し", "ゃ", "ば", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-239",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "医院",
      answer: ["い", "い", "ん"],
      choices: ["い", "い", "ん", "に", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-240",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "入院",
      answer: ["に", "ゅ", "う", "い", "ん"],
      choices: ["に", "ゅ", "う", "い", "ん", "に"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-241",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "大学院",
      answer: ["だ", "い", "が", "く", "い", "ん"],
      choices: ["だ", "い", "が", "く", "い", "ん"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-242",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "病院",
      answer: ["び", "ょ", "う", "い", "ん"],
      choices: ["び", "ょ", "う", "い", "ん", "ひ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-243",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "理科",
      answer: ["り", "か"],
      choices: ["り", "か", "れ", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-244",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "理由",
      answer: ["り", "ゆ", "う"],
      choices: ["り", "ゆ", "う", "い", "よ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-245",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "料理",
      answer: ["り", "ょ", "う", "り"],
      choices: ["り", "ょ", "う", "り", "りょ", "る"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-246",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "地理",
      answer: ["ち", "り"],
      choices: ["ち", "り", "じ", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-247",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "化学",
      answer: ["か", "が", "く"],
      choices: ["か", "が", "く", "き", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-248",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "文学",
      answer: ["ぶ", "ん", "が", "く"],
      choices: ["ぶ", "ん", "が", "く", "ふ", "け"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-249",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "経済",
      answer: ["け", "い", "ざ", "い"],
      choices: ["け", "い", "ざ", "い", "げ", "さ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-250",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "済む",
      answer: ["す", "む"],
      choices: ["す", "む", "ず", "め"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-251",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "景色",
      answer: ["け", "し", "き"],
      choices: ["け", "し", "き", "げ", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-252",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "不足",
      answer: ["ふ", "そ", "く"],
      choices: ["ふ", "そ", "く", "ぷ", "ぞ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-253",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "遠足",
      answer: ["え", "ん", "そ", "く"],
      choices: ["え", "ん", "そ", "く", "あん", "ぞ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-254",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "足りる",
      answer: ["た", "り", "る"],
      choices: ["た", "り", "る", "だ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-255",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "体温計",
      answer: ["た", "い", "お", "ん", "け", "い"],
      choices: ["た", "い", "お", "ん", "け", "い"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-256",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "体育",
      answer: ["た", "い", "い", "く"],
      choices: ["た", "い", "い", "く", "だい"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-257",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "頭痛",
      answer: ["ず", "つ", "う"],
      choices: ["ず", "つ", "う", "す", "づ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-258",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "洗顔",
      answer: ["せ", "ん", "が", "ん"],
      choices: ["せ", "ん", "が", "ん", "ぜ", "か"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-259",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "顔色",
      answer: ["か", "お", "い", "ろ"],
      choices: ["か", "お", "い", "ろ", "が", "の"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-260",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "答える",
      answer: ["こ", "た", "え", "る"],
      choices: ["こ", "た", "え", "る", "ご", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-261",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "お祝い",
      answer: ["お", "い", "わ", "い"],
      choices: ["お", "い", "わ", "い", "に", "え"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-262",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "降りる",
      answer: ["お", "り", "る"],
      choices: ["お", "り", "る", "ぬ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-263",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "降る",
      answer: ["ふ", "る"],
      choices: ["ふ", "る", "ぷ", "ろ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-264",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "太い",
      answer: ["ふ", "と", "い"],
      choices: ["ふ", "と", "い", "ぷ", "ど"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-265",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "太陽",
      answer: ["た", "い", "よ", "う"],
      choices: ["た", "い", "よ", "う", "だい", "よ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-266",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "暗い",
      answer: ["く", "ら", "い"],
      choices: ["く", "ら", "い", "ぐ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-267",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "暗記",
      answer: ["あ", "ん", "き"],
      choices: ["あ", "ん", "き", "は", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-268",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "公園",
      answer: ["こ", "う", "え", "ん"],
      choices: ["こ", "う", "え", "ん", "ご", "あん"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-269",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "動物園",
      answer: ["ど", "う", "ぶ", "つ", "え", "ん"],
      choices: ["ど", "う", "ぶ", "つ", "え", "ん"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-270",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "庭園",
      answer: ["て", "い", "え", "ん"],
      choices: ["て", "い", "え", "ん", "で", "あん"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-271",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "港",
      answer: ["み", "な", "と"],
      choices: ["み", "な", "と", "ぬ", "ど"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-272",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "空港",
      answer: ["く", "う", "こ", "う"],
      choices: ["く", "う", "こ", "う", "ぐ", "ご"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-273",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "海岸",
      answer: ["か", "い", "が", "ん"],
      choices: ["か", "い", "が", "ん", "が", "か"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-274",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "彼氏",
      answer: ["か", "れ", "し"],
      choices: ["か", "れ", "し", "が", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-275",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "彼女",
      answer: ["か", "の", "じ", "ょ"],
      choices: ["か", "の", "じ", "ょ", "が", "じょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-276",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "紹介",
      answer: ["し", "ょ", "う", "か", "い"],
      choices: ["し", "ょ", "う", "か", "い", "じ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-277",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "お正月",
      answer: ["お", "し", "ょ", "う", "が", "つ"],
      choices: ["お", "し", "ょ", "う", "が", "つ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-278",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "正解",
      answer: ["せ", "い", "か", "い"],
      choices: ["せ", "い", "か", "い", "ぜ", "が"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-279",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "正直",
      answer: ["し", "ょ", "う", "じ", "き"],
      choices: ["し", "ょ", "う", "じ", "き", "じょ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-280",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "泳ぐ",
      answer: ["お", "よ", "ぐ"],
      choices: ["お", "よ", "ぐ", "ぬ", "く"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-281",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "水泳",
      answer: ["す", "い", "え", "い"],
      choices: ["す", "い", "え", "い", "ず", "え"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-282",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "春休み",
      answer: ["は", "る", "や", "す", "み"],
      choices: ["は", "る", "や", "す", "み", "ば"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-283",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "青春",
      answer: ["せ", "い", "し", "ゅ", "ん"],
      choices: ["せ", "い", "し", "ゅ", "ん", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-284",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "夏休み",
      answer: ["な", "つ", "や", "す", "み"],
      choices: ["な", "つ", "や", "す", "み", "だ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-285",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "秋休み",
      answer: ["あ", "き", "や", "す", "み"],
      choices: ["あ", "き", "や", "す", "み", "い"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-286",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "冬休み",
      answer: ["ふ", "ゆ", "や", "す", "み"],
      choices: ["ふ", "ゆ", "や", "す", "み", "ぷ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-287",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "季節",
      answer: ["き", "せ", "つ"],
      choices: ["き", "せ", "つ", "ぎ", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-288",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "四季",
      answer: ["し", "き"],
      choices: ["し", "き", "じ", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-289",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "漢字",
      answer: ["か", "ん", "じ"],
      choices: ["か", "ん", "じ", "が", "し"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-290",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "字引",
      answer: ["じ", "び", "き"],
      choices: ["じ", "び", "き", "し", "ひ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-291",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "親切",
      answer: ["し", "ん", "せ", "つ"],
      choices: ["し", "ん", "せ", "つ", "じ", "ぜ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-292",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "父親",
      answer: ["ち", "ち", "お", "や"],
      choices: ["ち", "ち", "お", "や", "ぢ", "に"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-293",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "母親",
      answer: ["は", "は", "お", "や"],
      choices: ["は", "は", "お", "や", "ば", "に"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-294",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "切る",
      answer: ["き", "る"],
      choices: ["き", "る", "ぎ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-295",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "切符",
      answer: ["き", "っ", "ぷ"],
      choices: ["き", "っ", "ぷ", "ぎ", "ふ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-296",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "大切",
      answer: ["た", "い", "せ", "つ"],
      choices: ["た", "い", "せ", "つ", "だい"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-297",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "便利な",
      answer: ["べ", "ん", "り", "な"],
      choices: ["べ", "ん", "り", "な", "へ", "れ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-298",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "不便な",
      answer: ["ふ", "べ", "ん", "な"],
      choices: ["ふ", "べ", "ん", "な", "ぷ", "は"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-299",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "利用",
      answer: ["り", "よ", "う"],
      choices: ["り", "よ", "う", "い", "よ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },
    {
      id: "td-n4-c-300",
      kind: "tile-drop",
      type: "reading",
      sectionId: "moji-goi",
      prompt: "教室",
      answer: ["き", "ょ", "う", "し", "つ"],
      choices: ["き", "ょ", "う", "し", "つ", "ぎ"],
      difficulty: "N4",
      enabled: true,
      quizType: "japanese-n4",
    },

  ],
}

export function getTileDropPool(quizType: QuizType) {
  const list = tileDropPools[quizType] ?? []
  return list.filter((q) => q.enabled && q.kind === "tile-drop")
}
